
CREATE TABLE `route_configuration` (
  `route_id` varchar(6) NOT NULL,
  `route_desc` varchar(50) NOT NULL,
  `is_txn_route` tinyint(3) NOT NULL DEFAULT 0,
  `is_promo_route` tinyint(3) NOT NULL DEFAULT 0,
  `is_intl_route` tinyint(3) NOT NULL DEFAULT 0,
  `route_type` varchar(4) NOT NULL DEFAULT 'SMPP',
  `kannel_ip` varchar(20) NOT NULL DEFAULT 'NA',
  `kannel_port` int(10) NOT NULL DEFAULT 0,
  `kannel_status_port` int(5) NOT NULL DEFAULT 5000,
  `kannel_store_size_max_limit` int(9) NOT NULL DEFAULT 100000,
  `smscid` varchar(10) DEFAULT NULL,
  `isprefix` tinyint(3) DEFAULT NULL,
  `prefix` char(3) DEFAULT NULL,
  `promo_header` varchar(15) DEFAULT NULL,
  `header_whitelisted` tinyint(4) NOT NULL DEFAULT 0,
  `promo_header_type` tinyint(4) DEFAULT NULL,
  `response` varchar(10) DEFAULT NULL,
  `dtime_format` varchar(25) NOT NULL,
  `ignore_status` varchar(50) DEFAULT NULL,
  `ignore_mnumber_for_select` char(1) NOT NULL DEFAULT '0',
  `load_balancer_yn` decimal(1,0) DEFAULT 0,
  `is_dlt_route` decimal(1,0) DEFAULT 0,
  `is_dummy_route` tinyint(3) NOT NULL DEFAULT 0,
  `carrier_full_dn` varchar(100) NOT NULL DEFAULT 'id:1 sub:001 dlvrd:001 submitdate:{0} donedate:{1} stat:DELIVRD err:000 Text:null',
  `updated_ts` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`route_id`),
  CONSTRAINT `route_configuration_FK` FOREIGN KEY (`route_id`) REFERENCES `carrier_route_map` (`route_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

