CREATE TABLE `url_redirect_log` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `client_id` varchar(16) NOT NULL,
  `dest` varchar(15) NOT NULL,
  `msg_id` varchar(25) NOT NULL,
  `hdr` varchar(15) DEFAULT NULL,
  `campaign_id` varchar(100) DEFAULT NULL,
  `campaign_name` varchar(100) DEFAULT NULL,
  `msg_recv_time` datetime(3) DEFAULT NULL,
  `cli_msg_id` varchar(50) DEFAULT NULL,
  `ipaddress` varchar(18) DEFAULT NULL,
  `countrycode` varchar(5) DEFAULT NULL,
  `country` varchar(50) DEFAULT NULL,
  `region` varchar(50) DEFAULT NULL,
  `city` varchar(50) DEFAULT NULL,
  `longitute` float DEFAULT NULL,
  `latitude` float DEFAULT NULL,
  `osname` varchar(50) DEFAULT NULL,
  `osgroup` varchar(50) DEFAULT NULL,
  `browsername` varchar(50) DEFAULT NULL,
  `browserversion` varchar(25) DEFAULT NULL,
  `devicename` varchar(50) DEFAULT NULL,
  `requesttime` datetime(3) DEFAULT NULL,
  `smartlinkid` varchar(10) DEFAULT NULL,
  `shortenurl` varchar(50) DEFAULT NULL,
  `shortcode` varchar(100) DEFAULT NULL,
  `redirecturl` varchar(200) DEFAULT NULL,
  `useragent` text DEFAULT NULL,
  `customparams` varchar(200) DEFAULT NULL,
  `status` varchar(100) DEFAULT NULL,
  `created_ts` datetime(3) DEFAULT current_timestamp(3) ON UPDATE current_timestamp(3),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=497368 DEFAULT CHARSET=utf8 
