insert into component(component_name,description) values('account_sync','Account sync');
insert into component(component_name,description) values('aging_dn_processor','Aging Dlr Processor');
insert into component(component_name,description) values('aging_insert','Aging Insert Processor');
insert into component(component_name,description) values('blockout_wallet_consumer','Blockout Wallet Consumer');
insert into component(component_name,description) values('capping_chk','Capping Check');
insert into component(component_name,description) values('carrier_handover','Carrier Handover component for the platfrom');
insert into component(component_name,description) values('client_dlr_handover','Client Dlr Handover via SMPP  HTTP DLR_QUERY');
insert into component(component_name,description) values('client_dlr_handover_http','Client Dlr Handover via HTTP');
insert into component(component_name,description) values('dlr_internal_process ','Dlr Internal Processor');
insert into component(component_name,description) values('dlr_processor','Dlr Processor');
insert into component(component_name,description) values('dlr_query_dn','Dlr Query for DN request');
insert into component(component_name,description) values('dlr_query_mt','Dlr Query for MT request');
insert into component(component_name,description) values('dlr_receiver','Dlr Receiver');
insert into component(component_name,description) values('dlr_retry','Dlr Retry processor for Tempararry Carrier Failuer');
insert into component(component_name,description) values('dlr_wait_retry','Dlr retry for wait and delivery');
insert into component(component_name,description) values('dlt_verify_consumer','DLT Verify Consumer');
insert into component(component_name,description) values('dn_payload','Dlr payload store in redis');
insert into component(component_name,description) values('dummy_carrier_handover','Dummy Carrier Handover');
insert into component(component_name,description) values('duplicate_chk','Duplicate Check');
insert into component(component_name,description) values('duplicate_dn','Duplicate Check in SingleDN process');
insert into component(component_name,description) values('final_process_dn','Final DLR Processor for Billing ');
insert into component(component_name,description) values('final_process_mt','Final Biller Process for MT');
insert into component(component_name,description) values('http_dlr_handover','Http Dlr Handover');
insert into component(component_name,description) values('interface_async_process','Interface Async Process');
insert into component(component_name,description) values('interface_consumer','Input Reader for Primary Redis');
insert into component(component_name,description) values('intrim_dlr','Intrim Dlr for Redis Configuration');
insert into component(component_name,description) values('kafka_service','Kafka Service');
insert into component(component_name,description) values('kannel_redis','Kannel Availability and Store Size Check');
insert into component(component_name,description) values('messageid_generator','Message Identifier Generator');
insert into component(component_name,description) values('optin_chk','Optin Check');
insert into component(component_name,description) values('platform_rejection_consumer','Platfrom Rejection Consumer Component');
insert into component(component_name,description) values('pri_dnd_chk','Primary DND Check');
insert into component(component_name,description) values('pri_optout_chk','Primary Optout Check');
insert into component(component_name,description) values('retry_carrier_handover','Retry Carrier Handover');
insert into component(component_name,description) values('router_consumer','Route finder logic component for the platform');
insert into component(component_name,description) values('schedule_blockout_consumer','Sche / Blockout consumer');
insert into component(component_name,description) values('schedule_blockout_consumer_verify','Verify  the msg belongs to Sch / Blockout.');
insert into component(component_name,description) values('sec_dnd_chk','Secondary DND Check');
insert into component(component_name,description) values('sec_optout_chk','Secondary Optout Check');
insert into component(component_name,description) values('shortcode_provider','Short Code Provider component');
insert into component(component_name,description) values('single_dlr_processor','Single Dlr Processor');
insert into component(component_name,description) values('smpp_client_dn','SMPP DN Client Redis');
insert into component(component_name,description) values('smpp_concat','SMPP Concatenate Redis');
insert into component(component_name,description) values('smpp_consumer','SMPP Consumer');
insert into component(component_name,description) values('smpp_dlr_handover','Smpp Dlr Handover');
insert into component(component_name,description) values('smpp_session','SMPP Session Information');
insert into component(component_name,description) values('submission_billing_consumer','Submission Billing Consumer');
insert into component(component_name,description) values('t2db_blockout','blockout');
insert into component(component_name,description) values('t2db_client_handover_log','Topic to Table for the Client Handover log');
insert into component(component_name,description) values('t2db_client_handover_master_log','Topic to Table for the Client Handover  Master Log');
insert into component(component_name,description) values('t2db_client_handover_retry_data','Topic to Table for the Client Handover Retry data');
insert into component(component_name,description) values('t2db_deliveries','deliveries');
insert into component(component_name,description) values('t2db_dn_error_based_retry','dn_error_based_retry');
insert into component(component_name,description) values('t2db_error_log','error_log');
insert into component(component_name,description) values('t2db_full_message','full_message');
insert into component(component_name,description) values('t2db_interim_deliveries','interim_deliveries');
insert into component(component_name,description) values('t2db_interim_failuers','interim_failuers');
insert into component(component_name,description) values('t2db_no_payload_dn','no_payload_dn');
insert into component(component_name,description) values('t2db_schedule','schedule');
insert into component(component_name,description) values('t2db_smpp_post_log','smpp_post_log');
insert into component(component_name,description) values('t2db_submission','submission');
insert into component(component_name,description) values('timebound_chk','Message Time Bound Check');
insert into component(component_name,description) values('update_aging','Aging Update Processor');
insert into component(component_name,description) values('verify_consumer','Message Verify Component for the platform');
insert into component(component_name,description) values('visulaized_link_consumer','R3C Consumer');
insert into component(component_name,description) values('wallet_chk','wallet_chk');
insert into component(component_name,description) values('wallet_consumer','Wallet Consumer');

