INSERT INTO `app_config_values` VALUES
('accesskey.params','pin,password','Alternate Accesskey Input Params'),
('allow.special.chars','e282b9,e282ac,e282a4','Allow special charts UC identifier'),
('base.currency','INR','Platform Base Currency Value'),
('billing.schema.date.format','_yyyyMM','Billing schema date format'),
('billing.table.date.format','_yyyyMMdd','Billing table date format'),
('billing.table.datewise.enabled','1','Require Date wise billing tables.'),
('bypass.global.timebound.check','0','Bypass the global Timebound check '),
('bypass.mobile.route','0','Bypass the Mobile Route Check'),
('carrier.success.status','200','Carrier Success Status Code'),
('custom.pattern.check','0','0 - Disable, 1 - Enable ( Do the client pattern check)'),
('default.carrier.value','others','Default Carier Value'),
('default.circle.value','others','Default Circle Value'),
('default.country.code','IND','Default Country Code'),
('delete.redis.keys.max.fetch.len','100','Maximum fetch delete keys'),
('dest.max.length','15','Maximum Destination length allow'),
('dest.min.length','5','Minimum Destination Length allow'),
('dlr.gen.mysql.payload.size','500','Generate Dlr from payload mysql fetch size'),
('dlr.gen.payload.size','500','Generate Dlr Payload size'),
('dlr.url.template','http://{0}:{1}/dnr/dlrreceiver?dr=%a&smscid=%i&statuscd=%d&add_info={2}&systemid=%o','kannel callback dlr url template'),
('dlt.param.max.length','20','DLT TemplateId & EntityId Maximum Length'),
('dlt.praram.min.length','6','DLT TemplateId & EntityId Minimum Length'),
('dlt_enable','1','Global DLT enable'),
('dn.delv.status.code','600','DN Success Status Code'),
('domestic.global.faillist.chk','0','Enable/Disable Global Faillist Check for all customer'),
('five.digit.shortcode.sla','45','R3C five digit schort SLA'),
('gen.dlr.from.payload.interval.in.hrs','1','Generate Dlr from payload interval'),
('global.dn.adjustment.in.sec','1','Global DTime adjustment in seconds'),
('global.msg.max.validity.insec','86410','Message avlidity Time'),
('global.timebound.enabled','0','Global Timebound check is enabled'),
('global.timebound.request.count','2','Global Timebound Max Requests allow'),
('global.timebound.time.interval.sec','120','Global Timebound check process Interval in seconds'),
('httpclienthandover.default.batch.size','1000','Default queue batch size'),
('httpclienthandover.default.thread.count','10','Default queue thread count'),
('httpclienthandover.log.retry.attempt','1','Http Clienthandover global log all records'),
('intl.base.currency','EUR','Platform Base Currency Value'),
('intl.header.max.length','15','Intl Header Maximum Length'),
('intl.header.min.length','1','Intl Header Minumum Length'),
('is.kafka.available','1','Can send request to kafka'),
('max.no.payload.retry.attempt.count','50','20 retry during payload redis down'),
('max.r3c.elastic.retry.count','3','Elastic Fail Retry count'),
('max.route.retry.attempt.count','5','Max Route Retry Attempt Count'),
('max.split.part.allow','30','Maximum Message Parts allow to Platform'),
('msc.code.split.chk','6','To identify Carrier & Circle'),
('nack.error.code','-998','NACK Operator Error Code'),
('nopayload.for.promo.msg','1','Payload store not require for Pramotional Messages'),
('payloadgen.fail.status.flag','FAILED','Generate DN from payload failure status flag'),
('payloadgen.fail.status.id','-788','Generate DN from payload failure status id'),
('payloadgen.success.status.flag','DELIVRD','Generate DN from payload success status flag'),
('payloadgen.success.status.id','-787','Generate DN from payload success status id'),
('platform.decimal.prcecision.data.process','12','Decimal places to be used while processing data'),
('platform.decimal.prcecision.data.store','12','Decimal places to be used while storing data'),
('platform.decimal.prcecision.round.mode','0','Decimal places rounding mode. 0-UP, 1-DOWN, 2-CEILING, 3-FLOOR, 4-HALF_UP, 5-HALF_DOWN, 6-HALF_EVEN'),
('r3c.default.domain.url','c3r.in','Default R3C domain URL'),
('r3c.insert.type','PB','r3c.insert.type'),
('r3c.jndiinfo.id','12','r3c.jndiinfo.id'),
('r3r.device.location.access.key','afccccda02396c7c23b848f5b6e3a1980b9671966dee7a7a7098378488cea8a8','R3R device location find url access key'),
('r3r.device.location.access.url','http://api.ipinfodb.com/v3/ip-city','R3R device location find url'),
('require.udh.validation','1','UDH Validation required'),
('schedule.max.time','129600','Maximum schedule message allow time'),
('schedule.min.time','15','Minimum schedule message allow time'),
('six.digit.shortcode.sla','60','R3C six digit schort SLA'),
('smpp.concat.message.expiry.in.sec','1800','Smpp Concat Message Expiry in seconds'),
('smpp.dn.max.expiry.in.sec','21600','Smpp DN Max Expiry in seconds '),
('smpp.max.expiry.minutes.allowed','3600','SMPP Max Message Expiry Allow'),
('sms.template.max.dynamic.argument','6','Maximum Templates Values allow'),
('sms.template.max.params','6','Template message maximum dynamic arguments allow'),
('timebound.redis.keys.max.fetch.len','10','Maximum Timebound redis keys fetch'),
('trai.blockout.end','10:00','TRAI Blockout end time'),
('trai.blockout.start','21:00','TRAI Blockout start time'),
('vl.exclude.url.ends.with','#@#','R3C exclude url ends delimiter'),
('vl.exclude.url.starts.with','#@#','R3C exclude url starts delimiter'),
('vl.url.ends.with','#R#','R3C url ends delimiter'),
('vl.url.starts.with','#R#','R3C url starts delimiter');
