INSERT INTO `error_code_mapping` VALUES
('100','Success','INTERFACE','Application Accepted','Success','Submitted to Carrier','Success',NULL,0,0,0),
('310','Invalid Encrypt value','INTERFACE','Invalid Encrypt value','Rejected','Platform Rejection','',NULL,0,0,0),
('311','Empty Mobile Number','INTERFACE','Empty Mobile Number','Rejected','Platform Rejection','',NULL,0,0,0),
('312','Mobile Number is not valid','INTERFACE','Mobile Number is not valid','Rejected','Platform Rejection','',NULL,0,0,0),
('313','Empty Message','INTERFACE','Empty Message','Rejected','Platform Rejection','Invalid Requests',NULL,0,0,0),
('314','Schedule Feature Disabled','INTERFACE','Schedule Feature Disabled','Rejected','Platform Rejection','',NULL,0,0,0),
('315','Invalid schedule time','INTERFACE','Invalid schedule time','Rejected','Platform Rejection','',NULL,0,0,0),
('316','Exceed Schedule Time','INTERFACE','Exceed Schedule Time','Rejected','Platform Rejection','',NULL,0,0,0),
('317','Message Type is not valid','INTERFACE','Message Type is not valid','Rejected','Platform Rejection','',NULL,0,0,0),
('318','Destination Port is not valid','INTERFACE','Destination Port is not valid','Rejected','Platform Rejection','',NULL,0,0,0),
('319','Expiry Value is not valid','INTERFACE','Expiry Value is not valid','Expired','Platform Rejection','',NULL,0,0,0),
('320','Invalid Expiry Time','INTERFACE','Invalid Expiry Time','Rejected','Platform Rejection','',NULL,0,0,0),
('321','Append Country code is not valid','INTERFACE','Append Country code is not valid','Rejected','Platform Rejection','',NULL,0,0,0),
('322','URL Track is not valid','INTERFACE','URL Track is not valid','Rejected','Platform Rejection','',NULL,0,0,0),
('324','Customer Reference Id exceeds length','INTERFACE','Customer Reference Id exceeds length','Rejected','Platform Rejection','',NULL,0,0,0),
('325','Message Send failed - TRA Blockout Time ','INTERFACE','Message Send failed - TRA Blockout Time ','Rejected','Platform Rejection','',NULL,0,0,0),
('326','Message Send failed - Schedule Time is with in TRA Blockout Time','INTERFACE','Message Send failed - Schedule Time is with in TRA Blockout Time','Rejected','Platform Rejection','',NULL,0,0,0),
('327','UDHI is not valid','INTERFACE','UDHI is not valid','Rejected','Platform Rejection','',NULL,0,0,0),
('328','Invalid Data Coding Value','INTERFACE','Invalid Data Coding Value','Rejected','Platform Rejection','',NULL,0,0,0),
('329','Invalid Header - Empty Header','INTERFACE','Invalid Header - Empty Header','Rejected','Platform Rejection','',NULL,0,0,0),
('330','Invalid Header','INTERFACE','Invalid Header','Rejected','Platform Rejection','',NULL,0,0,0),
('331','Unauthorized Request','INTERFACE','Unauthorized Request','Rejected','Platform Rejection','',NULL,0,0,0),
('332','Template Id is not valid','INTERFACE','Template Id is not valid','Rejected','Platform Rejection','',NULL,0,0,0),
('333','Empty Template Values','INTERFACE','Empty Template Values','Rejected','Platform Rejection','',NULL,0,0,0),
('334','UDH is not valid','INTERFACE','UDH is not valid','Rejected','Platform Rejection','',NULL,0,0,0),
('335','Empty Reporting Key','INTERFACE','Empty Reporting Key','Rejected','Platform Rejection','',NULL,0,0,0),
('336','DLT Entity Id is not valid','INTERFACE','DLT Entity Id is not valid','Rejected','Platform Rejection','',NULL,0,0,0),
('337','DLT Template Id is not valid','INTERFACE','DLT Template Id is not valid','Rejected','Platform Rejection','',NULL,0,0,0),
('339','API Service Disabled','INTERFACE','API Service Disabled','Rejected','Platform Rejection','Account Rejection',NULL,0,0,0),
('340','International Service Disabled','INTERFACE','International Service Disabled','Rejected','Platform Rejection','Account Rejection',NULL,0,0,0),
('341','Invalid Country Code','INTERFACE','Invalid Country Code','Rejected','Platform Rejection','Invalid Requests',NULL,0,0,0),
('342','Smpp Throttle Limit Exceed','INTERFACE','Smpp Throttle Limit Exceed','Rejected','Platform Rejection','',NULL,0,0,0),
('343','Smpp Part Number Exceed Total Part Count','INTERFACE','Smpp Part Number Exceed Total Part Count','Rejected','Platform Rejection','',NULL,0,0,0),
('398','Internal Server Error','INTERFACE','Internal Server Error','Rejected','Platform Rejection','Others',NULL,0,0,0),
('399','Unknown Error Code','INTERFACE','Unknown Error','Failed',NULL,'',NULL,0,0,0),
('400','Success','PLATFORM','Success','Success','Not Applicable','Not Applicable','Not Applicable',0,0,0),
('401','System Error','PLATFORM','System Error','Failed','Platform Rejection','Others',NULL,0,0,0),
('402','DND Rejected','PLATFORM','DND Rejected','Rejected','Platform Rejection','Regulatory Rejection',NULL,0,0,0),
('403','Promotional message is not allowed','PLATFORM','Promotional message is not allowed','Rejected','Platform Rejection','Regulatory Rejection',NULL,0,0,0),
('404','Invalid Header','PLATFORM','Invalid Header','Rejected','Platform Rejection','Invalid Requests',NULL,0,0,0),
('405','Empty Feature Code','PLATFORM','Empty Feature Code','Rejected','Platform Rejection','Invalid Requests',NULL,0,0,0),
('406','Kannel Template Not Found','PLATFORM','System Error','Failed','Platform Rejection','Others','Others',0,0,0),
('407','Expired Message','PLATFORM','Expired Message','Expired','Platform Rejection','Policy Filterred','Others',0,0,0),
('408','Duplicate Check failed','PLATFORM','Duplicate Check failed','Rejected','Platform Rejection','Account Rejection',NULL,0,0,0),
('409','Global Header block failed','PLATFORM','Global Header block failed','Rejected','Platform Rejection','Policy Filterred',NULL,0,0,0),
('410','Global Mobile Number Block failed','PLATFORM','Global Mobile Number Block failed','Rejected','Platform Rejection','Policy Filterred',NULL,0,0,0),
('411','Route Based Header failed','PLATFORM','Route Based Header failed','Rejected','Platform Rejection','No Route Found',NULL,0,0,0),
('412','Specific Blockout failed','PLATFORM','Specific Blockout failed','Rejected','Platform Rejection','Account Rejection',NULL,0,0,0),
('413','TRA Blockout failed','PLATFORM','TRA Blockout failed','Rejected','Platform Rejection','Regulatory Rejection',NULL,0,0,0),
('414','Message Spam Filter failed','PLATFORM','Message Spam Filter failed','Rejected','Platform Rejection','Policy Filterred',NULL,0,0,0),
('415','SMS Blockout failed','PLATFORM','SMS Blockout failed','Rejected','Platform Rejection','Account Rejection',NULL,0,0,0),
('416','URL Shortner process failed','PLATFORM','URL Shortner process failed','Rejected','Platform Rejection','Invalid Requests',NULL,0,0,0),
('417','Wallet Check Failed','PLATFORM','Wallet Check Failed','Rejected','Platform Rejection','Account Rejection',NULL,0,0,0),
('418','Intl Credit Not Specified','PLATFORM','Intl Credit Not Specified','Rejected','Platform Rejection','Credits Expired',NULL,0,0,0),
('419','Invalid HEX message','PLATFORM','Invalid HEX message','Rejected','Platform Rejection','Invalid Requests',NULL,0,0,0),
('420','Invalid UDH','PLATFORM','Invalid UDH','Rejected','Platform Rejection','Invalid Requests',NULL,0,0,0),
('421','Invalid message','PLATFORM','Invalid message','Rejected','Platform Rejection','Invalid Requests',NULL,0,0,0),
('422','Empty Route id','PLATFORM','Empty Route id','Rejected','Platform Rejection','No Route Found',NULL,0,0,0),
('423','Invalid Route id','PLATFORM','Invalid Route id','Rejected','Platform Rejection','Invalid Requests',NULL,0,0,0),
('424','International Country Code Range not available','PLATFORM','International Country Code Range not available','Rejected','Platform Rejection','Invalid Requests',NULL,0,0,0),
('425','International Invalid Mobile Number length','PLATFORM','International Invalid Mobile Number length','Rejected','Platform Rejection','Invalid Requests',NULL,0,0,0),
('426','International Route Expired','PLATFORM','International Route Expired','Rejected','Platform Rejection','Account Rejection',NULL,0,0,0),
('427','All parts of Concat message not received','PLATFORM','All parts of Concat message not received','Rejected','Platform Rejection','Invalid Requests',NULL,0,0,0),
('428','International Invalid Route','PLATFORM','International Invalid Route','Rejected','Platform Rejection','No Route Found',NULL,0,0,0),
('429','International Service Disabled','PLATFORM','International Service Disabled','Rejected','Platform Rejection','Account Rejection',NULL,0,0,0),
('430','Header template check failed','PLATFORM','Invalid Header','Rejected','Platform Rejection','Invalid Requests',NULL,0,0,0),
('431','Reject Timebound check','PLATFORM','Reject Timebound check','Rejected','Platform Rejection','Account Rejection',NULL,0,0,0),
('432','Rejected in DLT Template check','PLATFORM','Rejected in DLT Template check','Rejected','Platform Rejection','Invalid Requests',NULL,0,0,0),
('433','Invalid DLT Entity id','PLATFORM','Invalid DLT Entity id','Rejected','Platform Rejection','Invalid Requests',NULL,0,0,0),
('434','Account Deactivated','PLATFORM','Account Deactivated','Rejected','Platform Rejection','Account Rejection',NULL,0,0,0),
('435','Account Suspended','PLATFORM','Account Suspended','Rejected','Platform Rejection','Account Rejection',NULL,0,0,0),
('436','Carrier Handover Failed','PLATFORM','Carrier Handover Failed','Rejected','Platform Rejection','',NULL,0,0,0),
('437','Submission DND Status','PLATFORM','Submission DND Status','Rejected','Platform Rejection',' ',NULL,0,0,0),
('438','Deliveries DND Status','PLATFORM','Deliveries DND Status','Rejected','Platform Rejection',' ',NULL,0,0,0),
('440','Customer Header Pool failed','PLATFORM','Customer Header Pool failed','Rejected','Platform Rejection','No Route Found',NULL,0,0,0),
('441','Promo Temporary failed','PLATFORM','Promo Temporary failed','Rejected','Platform Rejection','Invalid Requests',NULL,0,0,0),
('442','Exceed Max Split Parts','PLATFORM','Exceed Max Split Parts','Rejected','Platform Rejection',' ',NULL,0,0,0),
('443','Partially Carrier Handover Failed','PLATFORM','Partially Carrier Handover Failed','Rejected','Platform Rejection',' ',NULL,0,0,0),
('444','Invalid DLT Template Group Id','PLATFORM','Invalid DLT Template Group Id','Rejected','Platform Rejection','Invalid Requests',NULL,0,0,0),
('445','Insufficient Wallet Balance','PLATFORM','Insufficient Wallet Balance','Rejected','Platform Rejection','Account Rejection',NULL,0,0,0),
('446','Custom Mobile Number Black failed','PLATFORM','Custom Mobile Number Black failed','Rejected','Platform Rejection','Account Rejection',NULL,0,0,0),
('447','Price Conversion Failed','PLATFORM','Price Conversion Failed','Rejected','Platform Rejection','Others',NULL,0,0,0),
('448','Same UDH for All Parts','PLATFORM','Same UDH for All Parts','Rejected','Platform Rejection','Invalid Requests',NULL,0,0,0),
('449','UDH Total Part Mismatch','PLATFORM','UDH Total Part Mismatch','Rejected','Platform Rejection','Invalid Requests',NULL,0,0,0),
('450','Orphan Concat Expiry','PLATFORM','Orphan Concat Expiry','Rejected','Platform Rejection','Invalid Requests',NULL,0,0,0),
('451','Invalid Data Coding Scheme','PLATFORM','Invalid Data Coding Scheme','Rejected','Platform Rejection','Invalid Requests',NULL,0,0,0),
('452','Exceed Capping Limit','PLATFORM','Exceed Capping Limit','Rejected','Platform Rejection','Invalid Requests',NULL,0,0,0),
('499','Unknown Error Code','PLATFORM','Unknown Error','Failed',NULL,'',NULL,0,0,0),
('600','Delivered','OPERATOR','DELIVRD','Delivered','Submitted to Carrier','Delivered',NULL,0,0,0),
('601','Message Queue Exceeded','OPERATOR','EXP-MSG-Q-EXD','Expired','Submitted to Carrier','Temporary Failure','Handset Failure',1,0,0),
('602','SubscriberBusyForMT-SM','OPERATOR','EXP-HDST-BUSY','Expired','Submitted to Carrier','Temporary Failure','Handset Failure',1,0,0),
('603','Timeout','OPERATOR','EXP-SMS-TMOUT','Expired','Submitted to Carrier','Temporary Failure','Operator Failure',1,0,0),
('604','Timeout-SC','OPERATOR','EXP-NW-TMOUT','Expired','Submitted to Carrier','Temporary Failure','Operator Failure',1,0,0),
('605','SystemFailure','OPERATOR','EXP-NW-TMOUT','Expired','Submitted to Carrier','Temporary Failure','Operator Failure',1,0,0),
('606','SM-DeliveryFailure-MemCapExc','OPERATOR','EXP-MEM-EXCD','Expired','Submitted to Carrier','Temporary Failure','Handset Failure',1,0,0),
('607','AbsentSubscriber','OPERATOR','EXP-ABS-SUB','Expired','Submitted to Carrier','Temporary Failure','Handset Failure',1,0,0),
('608','Failed','OPERATOR','FAILED','Failed','Submitted to Carrier','Permanent Failure','Number Not Active',1,0,0),
('609','*','OPERATOR','Sub-SMSC','Pending','Submitted to Carrier','Pending',NULL,1,0,0),
('610','RemoteNodeNotReachable','OPERATOR','RemoteNodeNotReachable','Expired','Submitted to Carrier','Temporary Failure','Operator Failure',1,0,0),
('611','UserSpecificReason','OPERATOR','UserSpecificReason','Expired','Submitted to Carrier','Temporary Failure','Handset Failure',1,0,0),
('612','SmscBufferFlushed','OPERATOR','SmscBufferFlushed','Expired','Submitted to Carrier','Temporary Failure','Operator Failure',1,0,0),
('613','UnidentifiedSubscriber','OPERATOR','UnidentifiedSubscriber','Failed','Submitted to Carrier','Permanent Failure','Number Not Active',1,0,0),
('614','DLT Preference Filter','OPERATOR','DLT Preference Filter','Failed','Submitted to Carrier','Permanent Failure','DLT Related Filters',1,0,0),
('615','DLT System Error','OPERATOR','DLT System Error','Failed','Submitted to Carrier','Permanent Failure','DLT Related Filters',1,0,0),
('616','DLT Opt-out Filter','OPERATOR','DLT Opt-out Filter','Failed','Submitted to Carrier','Permanent Failure','DLT Related Filters',1,0,0),
('617','TEMPLATE_ID_NOT_FOUND','OPERATOR','DLT Template Filter','Failed','Submitted to Carrier','Permanent Failure','DLT Related Filters',1,0,0),
('618','TEMPLATE_ID_INACTIVE','OPERATOR','DLT Template Filter','Failed','Submitted to Carrier','Permanent Failure','DLT Related Filters',1,0,0),
('619','TEMPLATE_ID_BLACKLISTED','OPERATOR','DLT Template Filter','Failed','Submitted to Carrier','Permanent Failure','DLT Related Filters',1,0,0),
('620','CONTENT_NOT_MATCHED','OPERATOR','DLT Template Filter','Failed','Submitted to Carrier','Permanent Failure','DLT Related Filters',1,0,0),
('621','HEADER_NOT_REGISTERED_FOR_TEMPLATE','OPERATOR','DLT Template Filter','Failed','Submitted to Carrier','Permanent Failure','DLT Related Filters',1,0,0),
('622','VARIABLE_EXCEEDED_MAX_LENGTH','OPERATOR','DLT Template Filter','Failed','Submitted to Carrier','Permanent Failure','DLT Related Filters',1,0,0),
('623','ERROR_IDENTIFYING_TEMPLATE_ID','OPERATOR','DLT Template Filter','Failed','Submitted to Carrier','Permanent Failure','DLT Related Filters',1,0,0),
('624','INVALID_TEMPLATE_ID','OPERATOR','DLT Template Filter','Failed','Submitted to Carrier','Permanent Failure','DLT Related Filters',1,0,0),
('625','DLT Entity Filter','OPERATOR','DLT Entity Filter','Failed','Submitted to Carrier','Permanent Failure','DLT Related Filters',1,0,0),
('626','DLT TM Filter','OPERATOR','DLT TM Filter','Failed','Submitted to Carrier','Permanent Failure','DLT Related Filters',1,0,0),
('627','DLT Header Filter','OPERATOR','DLT Header Filter','Failed','Submitted to Carrier','Permanent Failure','DLT Related Filters',1,0,0),
('628','Invalid Request Format','OPERATOR','Invalid Request','Failed','Submitted to Carrier','Permanent Failure','Operator Failure',1,0,0),
('629','Barred unauthorized message originator','OPERATOR','Barred unauthorized message originator','Failed','Submitted to Carrier','Permanent Failure','Operator Failure',1,0,0),
('630','MO Not Supported','OPERATOR','MO Not Supported','Failed','Submitted to Carrier','Permanent Failure','Operator Failure',1,0,0),
('631','DND Reject','OPERATOR','DND Reject','Failed','Submitted to Carrier','Permanent Failure','Operator Failure',1,0,0),
('632','Call Barred','OPERATOR','Call Barred','Failed','Submitted to Carrier','Permanent Failure','Operator Failure',1,0,0),
('633','DLT Scrubbing TimeOut','OPERATOR','DLT Scrubbing TimeOut','Failed','Submitted to Carrier','Permanent Failure','Operator Failure',1,0,0),
('634','Header Blacklisted','OPERATOR','Header Blacklisted','Failed','Submitted to Carrier','Permanent Failure','Operator Failure',1,0,0),
('635','DLT Header Blocked','OPERATOR','DLT Header Blocked','Failed','Submitted to Carrier','Permanent Failure','Operator Failure',1,0,0),
('636','Roaming not supported','OPERATOR','Roaming not supported','Failed','Submitted to Carrier','Permanent Failure','Operator Failure',1,0,0),
('637','TEMPLATE_NOT_REGISTERED','OPERATOR','DLT Template Filter','Failed','Submitted to Carrier','Permanent Failure','DLT Related Filters',1,0,0),
('638','INVALID_TEMPLATE_TYPE','OPERATOR','DLT Template Filter','Failed','Submitted to Carrier','Permanent Failure','DLT Related Filters',1,0,0),
('639','Mobile Blacklist','OPERATOR','Mobile Blacklist','Failed','Submitted to Carrier','Permanent Failure','Operator Failure',1,0,0),
('640','Validity Expired','OPERATOR','Validity Expired','Expired','Submitted to Carrier','Permanent Failure','Operator Failure',1,0,0),
('641','Facility Not Supported','OPERATOR','Facility Not Supported','Failed','Submitted to Carrier','Permanent Failure','Operator Failure',1,0,0),
('642','NACK','OPERATOR','NACK','Failed','Submitted to Carrier','Permanent Failure','Operator Failure',1,1,0),
('643','Device Not Supported','OPERATOR','Device Not Supported','Failed','Submitted to Carrier','Permanent Failure','Operator Failure',1,0,0),
('644','Network Coverage Error','OPERATOR','Network Coverage Error','Failed','Submitted to Carrier','Permanent Failure','Operator Failure',1,0,0),
('645','Operation Disabled','OPERATOR','Operation Disabled','Failed','Submitted to Carrier','Permanent Failure','Operator Failure',1,0,0),
('646','Promo Blockout Time','OPERATOR','Promo Blockout Time','Failed','Submitted to Carrier','Permanent Failure','Operator Failure',1,0,0),
('647','Content Spam Filter','OPERATOR','Content Spam Filter','Failed','Submitted to Carrier','Permanent Failure','Operator Failure',1,0,0),
('648','Duplicate submission.','OPERATOR','Duplicate submission.','Failed','Submitted to Carrier','Permanent Failure','Operator Failure',1,0,0),
('699','Unknown Error Code','OPERATOR','Unknown Error','Failed',NULL,'',NULL,0,0,0);
