INSERT INTO `inmemory_loader_config` VALUES
('alternate_route','To load Alternate Routes',4,'select a.route_id,a.next_route_id,a.kannel_storesize,a.storesize_until_in_sec from rerouting_config a,route_configuration b where a.route_id=b.route_id and is_manual=\'0\'',1,30,'com.itextos.beacon.inmemory.carrierhandover.SmppRoutingConfig'),
('visualize_link','To load Visualize Link',10,'select * from r3c_smartlink_info',1,30,'com.itextos.beacon.inmemory.visualizelink.VisualizeLinkUtil'),
('include_visualize_link','To load include urls list to check the vl shorten',10,'select * from r3c_include_url',1,30,'com.itextos.beacon.inmemory.visualizelink.IncludeVisualizeLinks'),
('exclude_visualize_link','To load exclude urls list to bypass the vl shorten ',10,'select * from r3c_exclude_url',1,30,'com.itextos.beacon.inmemory.visualizelink.ExcludeVisualizeLinks'),
('intl_mobile_routes','To load the International Mobile Routes',4,'select * from intl_mobile_routes',1,30,'com.itextos.beacon.inmemory.routeinfo.cache.MobileNumberRouteInfo'),
('kannel_config_info','To load Kannel configuration to check the status',4,'select route_id, kannel_ip, kannel_port, kannel_status_port, kannel_store_size_max_limit from route_configuration',1,30,'com.itextos.beacon.inmemory.carrierhandover.KannelInfoHolder'),
('client_ignore_dn_gen','To load the Client ignore from DN Generate',5,'select * from acc_ignore_from_dn_generation where is_active=1 and ignore_or_generate=1',1,30,'com.itextos.beacon.inmemory.dnpayload.cache.PayloadExpiry'),
('application_config','To load application configuration',1,'select * from app_config_values',1,6,'com.itextos.beacon.inmemory.configvalues.ApplicationConfiguration'),
('japi_generic_response','To load Customized response configuration',2,'select cli_id, api_req_type, response_template, res_content_type, date_time_format, intf_status_Code, cli_status_code, cli_reason, cli_status_info, cli_http_status_code from api_custom_response acr, api_custom_response_error_code_mapping acrecm where acr.seq_no = acrecm.parent_seq_no',1,6,'com.itextos.beacon.inmemory.interfaces.cache.GenericResponse'),
('interface_msg_template','To load Interface SMS templates',3,'select cli_id, template_id,template from interface_sms_template',1,6,'com.itextos.beacon.inmemory.interfaces.cache.InterfaceSMSTemplate'),
('account_info','Loading user authentication information into memory',2,'select cli_id, user, ui_pass, api_pass, smpp_pass, acc_status from accounts_view',1,30,'com.itextos.beacon.inmemdata.account.dao.AccountInfo'),
('country_info','To load the country information',1,'select * from country_info',1,5,'com.itextos.beacon.inmemory.inmemdata.country.CountryInfoCollection'),
('account_msg_prefix_suffix','To load Message Prefix and Suffix values',1,'select * from client_msg_prefix_suffix',1,30,'com.itextos.beacon.inmemory.msgutil.cache.MessageSuffixPrefix'),
('intl_user_headers','To load the Intl Users Header Information',2,'select cli_id, header from user_headers_intl',1,30,'com.itextos.beacon.inmemory.userheader.IntlUserHeaderInfo'),
('govt_header_block','To load the Government Headers',4,'select * from govt_header',1,30,'com.itextos.beacon.inmemory.governmentheaders.GovtHeaderBlockCheck'),
('block_list_numbers','To load Block list number',3,'select SUBSTR(mnumber, 1, 5) as prefix, mnumber from listing.block_list_numbers where is_active =1',1,30,'com.itextos.beacon.inmemory.blocklistnumbers.BlockListNumberCheck'),
('custom_features','To load client specific fuature configuration',2,'select * from custom_features',1,30,'com.itextos.beacon.inmemory.customfeatures.InmemCustomFeatures'),
('table_inserter_info','To load topic2table configuration',1,'select * from topic2table_config',1,30,'com.itextos.beacon.platform.topic2table.dbinfo.TableInserterInfoCollection'),
('global_spam_block','To load the Global spam word config',3,'select * from block_list_spam_words where action<>0 order by action asc',1,30,'com.itextos.beacon.inmemory.spamcheck.GlobalSpamWords'),
('message_templates','To load Transaction Message Templates',3,'select template_id, cli_id,msg_template,encrypt, most_used_template from template_messages order by most_used_template',1,30,'com.itextos.beacon.inmemory.templates.LoadTemplates'),
('carrier_circle','To load Carrier & Circle information',1,'select SUBSTR(msc,1,4) prefix, msc, carrier, circle from configuration.msc_code_map ',1,30,'com.itextos.beacon.inmemory.msgutil.cache.CarrierCircles'),
('common_headers','To load global headers',3,'select * from block_list_headers',1,30,'com.itextos.beacon.inmemory.commonheader.CommonHeaders'),
('govt_header_exclude','To load Exclude Govt Headers',4,'select * from govt_header_exclude',1,30,'com.itextos.beacon.inmemory.governmentheaders.GovtHeaderExcludes'),
('govt_header_masking','To load Govt Header Masking',4,'select * from govt_header_masking',1,30,'com.itextos.beacon.inmemory.governmentheaders.GovtHeaderMasking'),
('common_msg_validity','To load Message Validity',4,'select priority, txn_validity, promo_validity from msg_validity',1,30,'com.itextos.beacon.inmemory.msgvalidity.CommonMsgValidity'),
('random_header','To load Random Headers',4,'select route_id,header from header_random_pool',1,30,'com.itextos.beacon.inmemory.commonlib.promoheaderpool.RandomHeaderPool'),
('custom_promo_header','To load Route Header Pool',4,'select route_id,header from route_headers_pool',1,30,'com.itextos.beacon.inmemory.promoheaderpool.CustomPromoHeaderPool'),
('alternate_header_route','To load Route Headers',4,'select * from header_alternate_routes',1,30,'com.itextos.beacon.inmemory.routeinfo.cache.AlternateHeaderRoute'),
('intl_client_keyword_header','To load Client Header Keyword Map',4,'select * from intl_client_header_template',1,30,'com.itextos.beacon.inmemory.routeinfo.cache.ClientKeywordHeaderInfo'),
('intl_priority_route','To load Intl priority routes',4,'select * from intl_country_header_template',1,30,'com.itextos.beacon.inmemory.routeinfo.cache.CountryKeywordHeadersInfo'),
('intl_client_country_series_header','To load intl Client wise Country series Headers',4,'select * from intl_client_route_info',1,30,'com.itextos.beacon.inmemory.routeinfo.cache.CountrySeriesHeaderInfo'),
('custom_route_template','To load Template based routing info',4,'select cli_id,template,most_used_pattern,route_id from template_based_routing order by most_used_pattern',1,30,'com.itextos.beacon.inmemory.routeinfo.cache.CustomRouteTemplates'),
('exceptions_spam_block','To load Exceptions Spam block',3,'select * from exceptions_spam_block_list order by cli_id desc',1,30,'com.itextos.beacon.inmemory.spamcheck.ExceptionalSpamWords'),
('intl_global_spam_block','To load Intl Global Spam block words',3,'select * from intl_block_list_spam_words where action<>0 order by action asc',1,30,'com.itextos.beacon.inmemory.spamcheck.IntlGlobalSpamWords'),
('voice_template_info','To load Voice Template Configuration',4,'select * from otp_voice_template_map',1,30,'com.itextos.beacon.inmemory.rr.cache.LoadVoiceMessageTemplate'),
('voice_acc_info','To load Voice Account Configuration',4,'select * from otp_voice_connect_map',1,30,'com.itextos.beacon.inmemory.rr.cache.LoadVoiceAccInfo'),
('global_retry_routes','To load Global retry route info',4,'select * from common_retry_route_config',1,30,'com.itextos.beacon.inmemory.rr.cache.LoadGlobalRetryRoutes'),
('global_retry_interval','To load Global retry interval info',4,'select * from common_retry_validity',1,30,'com.itextos.beacon.inmemory.rr.cache.LoadGlobalRetryInterval'),
('global_retry_info','To load Global retry info',4,'select * from retry_config',1,30,'com.itextos.beacon.inmemory.rr.cache.LoadGlobalRetryInfo'),
('custom_retry_routes','To load Client Wise Retry Routes',4,'select * from retry_route_config',1,30,'com.itextos.beacon.inmemory.rr.cache.LoadCustomRetryRoutes'),
('retry_msg_validity','To load Retry Message Validity',4,'select * from client_retry_validity',1,30,'com.itextos.beacon.inmemory.rr.cache.LoadCustomRetryMsgValidity'),
('alert_wait_config','To load Alert Wait Configuration',4,'select * from alert_wait_config',1,30,'com.itextos.beacon.inmemory.rr.cache.LoadAlertWaitConfig'),
('route_configuration','To load Routing Configuration',4,'select * from route_configuration',1,30,'com.itextos.beacon.inmemory.routeinfo.cache.RouteConfiguration'),
('priority_header_route','To load Priority Header Routes',4,'select * from header_priority_open_routes',1,30,'com.itextos.beacon.inmemory.routeinfo.cache.PriorityHeaderOpenRoute'),
('masked_header_pool','To load Masked Headers',4,'select * from header_mask_pool',1,30,'com.itextos.beacon.inmemory.routeinfo.cache.LoadMaskHeaderPool'),
('header_route_status','To load Header Route Status',4,'select * from header_route_status',1,30,'com.itextos.beacon.inmemory.routeinfo.cache.LoadHeeaderStatus'),
('default_routes','To load Default Routes',4,'select * from priority_routes',1,30,'com.itextos.beacon.inmemory.routeinfo.cache.LoadDefaultRoute'),
('mobile_routes','To load Mobile Routes',4,'select * from mobile_route_config',1,30,'com.itextos.beacon.inmemory.routeinfo.cache.LoadFirstAttemptMobileRoute'),
('custom_routes','To load Client Routes',4,'select * from client_route_config',1,30,'com.itextos.beacon.inmemory.routeinfo.cache.LoadCustomerRouteInfo'),
('carrier_support_headers','To load Carrier Support Headers',4,'select * from intl_carrier_support_headers',1,30,'com.itextos.beacon.inmemory.routeinfo.cache.LoadCarrierSupportHeaders'),
('intl_route_configuration','To load Intl Route Configuration',4,'select * from intl_route_config',1,30,'com.itextos.beacon.inmemory.intlrouteinfo.cache.IntlRouteConfiguration'),
('intl_route_headers','To load Intl Route Headers',4,'select * from intl_route_header',1,30,'com.itextos.beacon.inmemory.routeinfo.cache.IntlRouteHeader'),
('intl_global_header_keyword','To load Intl Global Header Keyword Map',4,'select * from intl_global_header_template',1,30,'com.itextos.beacon.inmemory.routeinfo.cache.IntlGlobalKeywordHeaderInfo'),
('route_groups','To load Route Groups',4,'select a.group,a.route_id,ratio,b.msg_type,is_intl_group FROM group_routes_ratio a,route_group_config b,route_configuration c where a.group=b.group and a.route_id=c.route_id',1,30,'com.itextos.beacon.inmemory.routeinfo.cache.GroupRoutesInfo'),
('fixed_header_route','To load Fixed Header Routes',4,'select * from header_fixed_routes',1,30,'com.itextos.beacon.inmemory.routeinfo.cache.FixedHeaderRoute'),
('msg_replace_rules','To load Message Replace Rules',4,'select * from msg_replace_route_condition',1,30,'com.itextos.beacon.inmemory.carrierhandover.MessageReplaceRules'),
('cluster_dn_receiver_info','To load Carrier Dlr Receiver component configuration ',1,'select * from dn_receiver_info',1,30,'com.itextos.beacon.inmemory.carrierhandover.ClusterDNReceiverInfo'),
('kannel_info','To load Kannel and route config Information',4,'select promo_header_type, promo_header, a.route_id, kannel_ip, kannel_port, smscid, isprefix, prefix, feature_cd, kannel_url, response, route_type, is_dlt_route, is_dummy_route, carrier_full_dn from kannel_url_config a, route_configuration b where a.route_id = b.route_id',1,30,'com.itextos.beacon.inmemory.carrierhandover.KannelInfoCache'),
('dn_receiver_conn_info','To load Dlr Receive Connection Info',1,'select * from dn_receiver_master',1,30,'com.itextos.beacon.inmemory.carrierhandover.DNReceiverInfo'),
('client_error_info','To load Client error code configuration',1,'select * from client_error_code',1,30,'com.itextos.beacon.inmemory.errorinfo.ClientErrorInfoCollection'),
('mobile_whitelist','To load White List Mobile Numbers',3,'select * from whitelist_mobiles',1,30,'com.itextos.beacon.inmemory.whitelistnumbers.MobileWhitelistNumbers'),
('exclude_circle','To load Circle Excludes info',1,'select cli_id, circle from circle_exclude_config',1,30,'com.itextos.beacon.inmemory.dnpayload.cache.ExcludeCircleInfo'),
('custom_slabs','Load Custom Slab configuration',1,'select a.parent_id, a.cli_id, a.start_in_sec as parent_start_insec, a.end_in_sec as parent_end_insec, b.child_id, b.start_in_sec as child_start_insec, b.end_in_sec as child_end_insec, b.percentage from dn_adjustment_parent a, dn_adjustment_child b where a.parent_id = b.parent_id',1,30,'com.itextos.beacon.inmemory.dnpayload.cache.CustomSlabs'),
('dlr_percentage_info','Load Dlr Percentage Info',4,'select * from dn_gen_percentage_map',1,30,'com.itextos.beacon.inmemory.dnpayload.cache.DlrPercentage'),
('dlr_client_percentage_info','Load Dlr Client Percentage Info',4,'select * from client_dn_gen_percentage_map',1,30,'com.itextos.beacon.inmemory.dnpayload.cache.DlrClientPercentage'),
('dlr_client_exclude','To load Dlr Client Exclude info',4,'select * from dn_gen_percentage_exempt',1,30,'com.itextos.beacon.inmemory.dnpayload.cache.DlrExclude'),
('bill_log_mapping','To load Bill loag suffix information',1,'select * from bill_log_map',1,30,'com.itextos.beacon.platform.msgflowutil.billing.BillLogMapCollection'),
('platform_error_info','To load the Plarform Error Code information',1,'select * from error_code_mapping',1,30,'com.itextos.beacon.inmemory.errorinfo.PlatformErrorInfoCollection'),
('carrier_error_info','To load the Carrier Error Code information',1,'select * from carrier_error_code',1,30,'com.itextos.beacon.inmemory.errorinfo.CarrierErrorInfoCollection'),
('client_dlr_pref','To load Client Dlr Preference configuration',2,'select * from client_handover_config_master',1,30,'com.itextos.beacon.inmemory.clidlrpref.ClientDlrConfigCollection'),
('dn_process_type_config','To load Single Dlr process configuration',2,'select * from client_dntype_config',1,30,'com.itextos.beacon.inmemory.customfeatures.InmemAccountDnTypeMappingInfo'),
('smpp_parent_child_acc_map','To load Parent and Child configuration for smpp message process',2,'select * from smpp_parrent_child_acc_map order by child_cli_id, parent_cli_id',1,30,'com.itextos.beacon.inmemory.customfeatures.InmemSmppParentChildAccountMap'),
('httpclienthandover_customer_info','To load the HttpClientHandover information',9,'select * from client_handover_config_master',1,30,'com.itextos.beacon.httpclienthandover.clientinfo.HttpCustomerInfoCollection'),
('intl_exceptions_spam_block','To load intl Exceptional Spam Block',3,'select * from intl_exceptions_spam_block_list order by cli_id desc',1,30,'com.itextos.beacon.inmemory.spamcheck.IntlExceptionalSpamWords'),
('ignore_dlr_gen','To ignore to generate DN\'s',5,'select * from acc_ignore_from_dn_generation',1,30,'com.itextos.beacon.inmemory.dnpayload.cache.ClientIngoreDnGenerate'),
('msg_type_spam_words_block','To load the Message Type Spam words Block check',3,'select * from block_list_spam_words_msgtype where action<>0 order by action asc',1,30,'com.itextos.beacon.inmemory.spamcheck.MsgTypeSpamWords'),
('intl_msg_type_spam_words_block','To load the Message Type Spam words Block check for Intl',3,'select * from intl_block_list_spam_words_msgtype where action<>0 order by action asc',1,30,'com.itextos.beacon.inmemory.spamcheck.IntlMsgTypeSpamWords'),
('currency_master','To load Currency Master',1,'select * from billing_currency_master',1,30,'com.itextos.beacon.platform.prepaiddata.inmemory.CurrencyMaster'),
('dlr_query','To load DlrQuery Data',9,'select cli_id, response_header_id from dlrquery_config_master where is_active=1',1,30,'com.itextos.beacon.inmemory.dlrquery.InmemDlrQuery'),
('encrypt_info','Encrypt Information',1,'select cli_id, incoming_crypto_type, incoming_crypto_alogrithm, billing_crypto_type, billing_crypto_algorithm, billing_crypto_columns, handover_crypto_type, handover_crypto_algorithm, incoming_crypto_param_1, incoming_crypto_param_2, incoming_crypto_param_3, incoming_crypto_param_4, incoming_crypto_param_5, billing_crypto_param_1, billing_crypto_param_2, billing_crypto_param_3, billing_crypto_param_4, billing_crypto_param_5, handover_crypto_param_1, handover_crypto_param_2, handover_crypto_param_3, handover_crypto_param_4, handover_crypto_param_5 from client_crypto_info',1,30,'com.itextos.beacon.inmemory.encryptinfo.EncryptInfoCollection'),
('dlt_msg_prefix_suffix','DLT Message Prefix ad Suffix',2,'select * from dlt_template_prefix_suffix',1,30,'com.itextos.beacon.inmemory.templates.DLTMsgTemplatePrefixSuffix'),
('domestic_user_headers','Domestic User Header Info',2,'select template_group_id, header, template_id, entity_id from dlt_template_group_header_entity_map',1,30,'com.itextos.beacon.inmemory.userheader.DomesticUserHeaderInfo'),
('client_block_list_numbers','To load Block list number',3,'select cli_id, SUBSTR(mnumber, 1, 5) as prefix, mnumber from listing.client_block_list_numbers where is_active = 1',1,30,'com.itextos.beacon.inmemory.blocklistnumbers.ClientBlockListNumberCheck'),
('smpp_account_info','To load Smpp Account Information',2,'select * from user_smpp_config',1,30,'com.itextos.beacon.inmemory.smpp.account.SmppAccountInfo'),
('currency_conversion_date_based','Currency Conversion based on Date wise',1,'select base_currency, quote_currency , rate from currency_rates_daily',1,10,'com.itextos.beacon.inmemory.currency.conversion.CurrencyCurrentDateReloader'),
('currency_conversion_month_based','Currency Conversion based on Month wise',1,'select base_currency, quote_currency , rate from currency_rates_monthly',1,10,'com.itextos.beacon.inmemory.currency.conversion.CurrencyCurrentMonthReloader'),
('intl_header_info','To load Intl Header Info',4,'select * from intl_country_header_info',1,30,'com.itextos.beacon.inmemory.routeinfo.cache.IntlHeaderInfo'),
('client_intl_rates','Client Intl Rates',1,'select * from client_intl_rates',1,30,'com.itextos.beacon.inmemory.msgutil.cache.ClientIntlCredits'),
('intl_country_rates','Country Intl Rates',1,'select * from intl_rates',1,30,'com.itextos.beacon.inmemory.msgutil.cache.IntlCredits'),
('client_msg_validity','To load Client Message Validity',4,'select cli_id, txn_validity, promo_validity from client_msg_validity',1,30,'com.itextos.beacon.inmemory.msgvalidity.ClientMsgValidity');
