insert into mnc(mcc,mnc,operator) values(365,10,trim('Digicel'));
insert into mnc(mcc,mnc,operator) values(365,840,trim('Cable AND Wireless'));
insert into mnc(mcc,mnc,operator) values(344,30,trim('Antigua Public Utilities Authority'));
insert into mnc(mcc,mnc,operator) values(344,50,trim('Antigua Wireless Ventures Limited'));
insert into mnc(mcc,mnc,operator) values(344,920,trim('Cable AND Wireless Caribbean Cellular Antigua Limited'));
insert into mnc(mcc,mnc,operator) values(344,930,trim('AT AND T Wireless'));
insert into mnc(mcc,mnc,operator) values(363,1,trim('Servicio di Telecomunicacion di Aruba'));
insert into mnc(mcc,mnc,operator) values(363,2,trim('Digicel Aruba'));
insert into mnc(mcc,mnc,operator) values(364,39,trim('The Bahamas Telecommunications Company Ltd BaTelCo'));
insert into mnc(mcc,mnc,operator) values(364,49,trim('Cable Bahamas Ltd'));
insert into mnc(mcc,mnc,operator) values(342,600,trim('LIME formerly known as Cable and Wireless'));
insert into mnc(mcc,mnc,operator) values(342,646,trim('KW Telecommunications Inc.'));
insert into mnc(mcc,mnc,operator) values(342,750,trim('Digicel Barbados Limited'));
insert into mnc(mcc,mnc,operator) values(342,800,trim('Ozone Wireless Inc.'));
insert into mnc(mcc,mnc,operator) values(342,820,trim('Neptune Communications Inc.'));
insert into mnc(mcc,mnc,operator) values(310,59,trim(''));
insert into mnc(mcc,mnc,operator) values(338,50,trim(''));
insert into mnc(mcc,mnc,operator) values(350,0,trim('Bermuda Digital Communications Ltd.'));
insert into mnc(mcc,mnc,operator) values(350,7,trim('Paradise Mobile'));
insert into mnc(mcc,mnc,operator) values(350,1,trim('Telecommunications Bermuda and West Indies Ltd'));
insert into mnc(mcc,mnc,operator) values(350,2,trim('M3 Wireless'));
insert into mnc(mcc,mnc,operator) values(350,5,trim('Telecom Networks'));
insert into mnc(mcc,mnc,operator) values(350,11,trim('Deltronics'));
insert into mnc(mcc,mnc,operator) values(350,15,trim('FKB Net Ltd.'));
insert into mnc(mcc,mnc,operator) values(348,170,trim('Cable and Wireless'));
insert into mnc(mcc,mnc,operator) values(348,370,trim('BVI Cable TV Ltd'));
insert into mnc(mcc,mnc,operator) values(348,570,trim('Caribbean Cellular Telephone'));
insert into mnc(mcc,mnc,operator) values(348,770,trim('Digicel BVI Limited'));
insert into mnc(mcc,mnc,operator) values(302,100,trim('Data on Tap Inc.'));
insert into mnc(mcc,mnc,operator) values(302,130,trim('Xplore Inc.'));
insert into mnc(mcc,mnc,operator) values(302,131,trim('Xplore Inc.'));
insert into mnc(mcc,mnc,operator) values(302,140,trim('Fibernetics Corp.'));
insert into mnc(mcc,mnc,operator) values(302,150,trim('Cogeco Connexion Inc.'));
insert into mnc(mcc,mnc,operator) values(302,151,trim('Cogeco Connexion Inc.'));
insert into mnc(mcc,mnc,operator) values(302,152,trim('Cogeco Connexion Inc.'));
insert into mnc(mcc,mnc,operator) values(302,220,trim('Telus Mobility'));
insert into mnc(mcc,mnc,operator) values(302,221,trim('Telus Mobility'));
insert into mnc(mcc,mnc,operator) values(302,222,trim('Telus Mobility'));
insert into mnc(mcc,mnc,operator) values(302,230,trim('ISP Telecom'));
insert into mnc(mcc,mnc,operator) values(302,250,trim('Bell Mobility'));
insert into mnc(mcc,mnc,operator) values(302,270,trim('Bragg Communications'));
insert into mnc(mcc,mnc,operator) values(302,290,trim('Airtel Wireless'));
insert into mnc(mcc,mnc,operator) values(302,300,trim('Ecotel inc.'));
insert into mnc(mcc,mnc,operator) values(302,310,trim('Ecotel inc.'));
insert into mnc(mcc,mnc,operator) values(302,320,trim('Rogers Communications'));
insert into mnc(mcc,mnc,operator) values(302,330,trim('Blue Canada Wireless Inc.'));
insert into mnc(mcc,mnc,operator) values(302,340,trim('Execulink'));
insert into mnc(mcc,mnc,operator) values(302,350,trim('Naskapi Imuun Inc.'));
insert into mnc(mcc,mnc,operator) values(302,360,trim('Telus Mobility'));
insert into mnc(mcc,mnc,operator) values(302,361,trim('Telus Mobility'));
insert into mnc(mcc,mnc,operator) values(302,370,trim('Fido Solutions Rogers Wireless'));
insert into mnc(mcc,mnc,operator) values(302,380,trim('Keewaytinook Okimakanak Mobile'));
insert into mnc(mcc,mnc,operator) values(302,390,trim('Dryden Mobility'));
insert into mnc(mcc,mnc,operator) values(302,420,trim('A.B.C. Allen Business Communications Ltd.'));
insert into mnc(mcc,mnc,operator) values(302,480,trim('SSi Connexions'));
insert into mnc(mcc,mnc,operator) values(302,490,trim('Quebecor'));
insert into mnc(mcc,mnc,operator) values(302,491,trim('Quebecor'));
insert into mnc(mcc,mnc,operator) values(302,500,trim('Videotron'));
insert into mnc(mcc,mnc,operator) values(302,510,trim('Videotron'));
insert into mnc(mcc,mnc,operator) values(302,520,trim('Videotron'));
insert into mnc(mcc,mnc,operator) values(302,530,trim('Keewaytinook Okimakanak Mobile'));
insert into mnc(mcc,mnc,operator) values(302,540,trim('Rovvr Communications Inc.'));
insert into mnc(mcc,mnc,operator) values(302,550,trim('Star Solutions International Inc.'));
insert into mnc(mcc,mnc,operator) values(302,560,trim('Lynx Mobility'));
insert into mnc(mcc,mnc,operator) values(302,570,trim('Ligado Networks Corp.'));
insert into mnc(mcc,mnc,operator) values(302,590,trim('Quadro Communications Co-op'));
insert into mnc(mcc,mnc,operator) values(302,600,trim('Iristel'));
insert into mnc(mcc,mnc,operator) values(302,610,trim('Bell Mobility'));
insert into mnc(mcc,mnc,operator) values(302,620,trim('ICE Wireless'));
insert into mnc(mcc,mnc,operator) values(302,630,trim('Bell Aliant'));
insert into mnc(mcc,mnc,operator) values(302,640,trim('Bell Mobility'));
insert into mnc(mcc,mnc,operator) values(302,650,trim('Thunder Bay Telephone'));
insert into mnc(mcc,mnc,operator) values(302,652,trim('BC Tel Mobility Telus'));
insert into mnc(mcc,mnc,operator) values(302,653,trim('Telus Mobility'));
insert into mnc(mcc,mnc,operator) values(302,655,trim('Bell MTS'));
insert into mnc(mcc,mnc,operator) values(302,656,trim('Thunder Bay Telephone Mobility'));
insert into mnc(mcc,mnc,operator) values(302,657,trim('Telus Mobility'));
insert into mnc(mcc,mnc,operator) values(302,660,trim('Bell MTS'));
insert into mnc(mcc,mnc,operator) values(302,670,trim('CityWest'));
insert into mnc(mcc,mnc,operator) values(302,680,trim('SaskTel Mobility'));
insert into mnc(mcc,mnc,operator) values(302,681,trim('SaskTel Mobility'));
insert into mnc(mcc,mnc,operator) values(302,690,trim('Bell Mobility'));
insert into mnc(mcc,mnc,operator) values(302,701,trim('MB Tel Mobility'));
insert into mnc(mcc,mnc,operator) values(302,702,trim('MT andT Mobility Aliant'));
insert into mnc(mcc,mnc,operator) values(302,703,trim('New Tel Mobility Aliant'));
insert into mnc(mcc,mnc,operator) values(302,710,trim(''));
insert into mnc(mcc,mnc,operator) values(302,720,trim('Rogers Communications'));
insert into mnc(mcc,mnc,operator) values(302,721,trim('Rogers Communications'));
insert into mnc(mcc,mnc,operator) values(302,730,trim('TerreStar Networks'));
insert into mnc(mcc,mnc,operator) values(302,740,trim('Rogers Communications'));
insert into mnc(mcc,mnc,operator) values(302,741,trim('Rogers Communications'));
insert into mnc(mcc,mnc,operator) values(302,750,trim('SaskTel Mobility'));
insert into mnc(mcc,mnc,operator) values(302,760,trim('Telus Mobility'));
insert into mnc(mcc,mnc,operator) values(302,770,trim('TNW Wireless Inc.'));
insert into mnc(mcc,mnc,operator) values(302,780,trim('SaskTel Mobility'));
insert into mnc(mcc,mnc,operator) values(302,781,trim('SaskTel Mobility'));
insert into mnc(mcc,mnc,operator) values(302,790,trim('NetSet Communications'));
insert into mnc(mcc,mnc,operator) values(302,820,trim('Rogers Communications'));
insert into mnc(mcc,mnc,operator) values(302,848,trim('Vocom International Telecommunications, Inc'));
insert into mnc(mcc,mnc,operator) values(302,860,trim('Telus Mobility'));
insert into mnc(mcc,mnc,operator) values(302,880,trim('Shared Telus, Bell, and SaskTel'));
insert into mnc(mcc,mnc,operator) values(302,910,trim('Halton Regional Police Service'));
insert into mnc(mcc,mnc,operator) values(302,920,trim('Rogers Communications'));
insert into mnc(mcc,mnc,operator) values(302,940,trim('Wightman Telecom'));
insert into mnc(mcc,mnc,operator) values(302,990,trim('Ericsson Canada'));
insert into mnc(mcc,mnc,operator) values(302,991,trim('Halton Regional Police Service'));
insert into mnc(mcc,mnc,operator) values(302,996,trim('Powertech Labs'));
insert into mnc(mcc,mnc,operator) values(302,997,trim('Powertech Labs'));
insert into mnc(mcc,mnc,operator) values(302,998,trim('Institut de Recherche d Hydro-Québec'));
insert into mnc(mcc,mnc,operator) values(338,5,trim('Digicel Cayman Ltd.'));
insert into mnc(mcc,mnc,operator) values(346,1,trim('WestTel Ltd.'));
insert into mnc(mcc,mnc,operator) values(346,140,trim('Cable and Wireless Cayman Islands Limited'));
insert into mnc(mcc,mnc,operator) values(346,50,trim('Digicel Cayman Ltd.'));
insert into mnc(mcc,mnc,operator) values(368,1,trim('Empresa de Telecomunicaciones de Cuba, SA'));
insert into mnc(mcc,mnc,operator) values(366,20,trim('Digicel Group Limited'));
insert into mnc(mcc,mnc,operator) values(366,110,trim('Cable  and Wireless'));
insert into mnc(mcc,mnc,operator) values(370,1,trim('Altice Group'));
insert into mnc(mcc,mnc,operator) values(370,2,trim('Compañía Dominicana de Teléfonos'));
insert into mnc(mcc,mnc,operator) values(370,3,trim('Altice Group'));
insert into mnc(mcc,mnc,operator) values(370,4,trim('Trilogy Dominicana, S.A.'));
insert into mnc(mcc,mnc,operator) values(370,5,trim('WIND Telecom, S.A'));
insert into mnc(mcc,mnc,operator) values(340,1,trim('Orange Caraïbe Mobiles'));
insert into mnc(mcc,mnc,operator) values(340,2,trim('Outremer Telecom'));
insert into mnc(mcc,mnc,operator) values(340,3,trim('UTS Caraïbe'));
insert into mnc(mcc,mnc,operator) values(340,4,trim('Free Caraïbe'));
insert into mnc(mcc,mnc,operator) values(340,8,trim('Dauphin Telecom'));
insert into mnc(mcc,mnc,operator) values(340,9,trim('Free Caraïbe'));
insert into mnc(mcc,mnc,operator) values(340,10,trim('Guadeloupe Téléphone Mobile'));
insert into mnc(mcc,mnc,operator) values(340,11,trim('Guyane Téléphone Mobile'));
insert into mnc(mcc,mnc,operator) values(340,12,trim('Martinique Téléphone Mobile'));
insert into mnc(mcc,mnc,operator) values(340,20,trim('DIGICEL Antilles Française Guyane'));
insert into mnc(mcc,mnc,operator) values(352,30,trim('Digicel Grenada Ltd.'));
insert into mnc(mcc,mnc,operator) values(352,110,trim('Cable and Wireless Grenada Ltd.'));
insert into mnc(mcc,mnc,operator) values(310,32,trim('PTI Pacifica Inc.'));
insert into mnc(mcc,mnc,operator) values(310,33,trim('Guam Telephone Authority'));
insert into mnc(mcc,mnc,operator) values(310,140,trim('Teleguam Holdings, LLC'));
insert into mnc(mcc,mnc,operator) values(310,400,trim('PTI Pacifica Inc.'));
insert into mnc(mcc,mnc,operator) values(310,470,trim('NTT DoCoMo Pacific'));
insert into mnc(mcc,mnc,operator) values(310,480,trim('PTI Pacifica Inc.'));
insert into mnc(mcc,mnc,operator) values(311,120,trim('PTI Pacifica Inc.'));
insert into mnc(mcc,mnc,operator) values(311,250,trim('PTI Pacifica Inc.'));
insert into mnc(mcc,mnc,operator) values(372,1,trim('Communication Cellulaire d Haiti S.A.'));
insert into mnc(mcc,mnc,operator) values(372,2,trim('Unigestion Holding S.A.'));
insert into mnc(mcc,mnc,operator) values(372,3,trim('NATCOM S.A.'));
insert into mnc(mcc,mnc,operator) values(338,20,trim('LIME Cable and Wireless'));
insert into mnc(mcc,mnc,operator) values(338,40,trim('Symbiote Investment Limited'));
insert into mnc(mcc,mnc,operator) values(338,5,trim('Digicel Jamaica Limited'));
insert into mnc(mcc,mnc,operator) values(338,70,trim('Oceanic Digital Jamaica Limited'));
insert into mnc(mcc,mnc,operator) values(338,80,trim('Rock Mobile Limited'));
insert into mnc(mcc,mnc,operator) values(338,110,trim('Cable and Wireless Communications'));
insert into mnc(mcc,mnc,operator) values(338,180,trim('Cable and Wireless Communications'));
insert into mnc(mcc,mnc,operator) values(334,1,trim('Comunicaciones Digitales Del Norte, S.A. de C.V.'));
insert into mnc(mcc,mnc,operator) values(334,10,trim('ATandT Mexico'));
insert into mnc(mcc,mnc,operator) values(334,20,trim('América Móvil'));
insert into mnc(mcc,mnc,operator) values(334,30,trim('Telefónica'));
insert into mnc(mcc,mnc,operator) values(334,40,trim('ATandT Mexico'));
insert into mnc(mcc,mnc,operator) values(334,50,trim('ATandT Mexico'));
insert into mnc(mcc,mnc,operator) values(334,60,trim('Servicios de Acceso Inalambrico, S.A. de C.V.'));
insert into mnc(mcc,mnc,operator) values(334,66,trim('Telefonos de México, S.A.B. de C.V.'));
insert into mnc(mcc,mnc,operator) values(334,70,trim('ATandT Mexico'));
insert into mnc(mcc,mnc,operator) values(334,80,trim('ATandT Mexico'));
insert into mnc(mcc,mnc,operator) values(334,90,trim('ATandT Mexico'));
insert into mnc(mcc,mnc,operator) values(334,100,trim('Telecomunicaciones de México'));
insert into mnc(mcc,mnc,operator) values(334,110,trim('Maxcom Telecomunicaciones, S.A.B. de C.V.'));
insert into mnc(mcc,mnc,operator) values(334,120,trim('Quickly Phone, S.A. de C.V.'));
insert into mnc(mcc,mnc,operator) values(334,130,trim('ALESTRA SERVICIOS MÓVILES, S.A. DE C.V.'));
insert into mnc(mcc,mnc,operator) values(334,140,trim('Altán Redes S.A.P.I. de C.V.'));
insert into mnc(mcc,mnc,operator) values(334,150,trim('Ultravisión, S.A. de C.V.'));
insert into mnc(mcc,mnc,operator) values(334,160,trim('Cablevisión Red, S.A. de C.V.'));
insert into mnc(mcc,mnc,operator) values(334,170,trim('Oxio Mobile, S.A. de C.V.'));
insert into mnc(mcc,mnc,operator) values(334,180,trim('FREEDOMPOP MÉXICO, S.A. DE C.V.'));
insert into mnc(mcc,mnc,operator) values(334,190,trim('VIASAT TECNOLOGÍA, S.A. DE C.V.'));
insert into mnc(mcc,mnc,operator) values(338,5,trim('Digicel'));
insert into mnc(mcc,mnc,operator) values(354,860,trim('Cable and Wireless'));
insert into mnc(mcc,mnc,operator) values(362,31,trim('Eutel N.V.'));
insert into mnc(mcc,mnc,operator) values(362,33,trim('WICC N.V.'));
insert into mnc(mcc,mnc,operator) values(362,51,trim('Telcell N.V.'));
insert into mnc(mcc,mnc,operator) values(362,54,trim('East Caribbean Cellular'));
insert into mnc(mcc,mnc,operator) values(362,59,trim('Liberty Latin America'));
insert into mnc(mcc,mnc,operator) values(362,60,trim('Liberty Latin America'));
insert into mnc(mcc,mnc,operator) values(362,63,trim('CSC N.V.'));
insert into mnc(mcc,mnc,operator) values(362,68,trim('Curaçao Telecom N.V.'));
insert into mnc(mcc,mnc,operator) values(362,69,trim('Curaçao Telecom N.V.'));
insert into mnc(mcc,mnc,operator) values(362,74,trim('PCS N.V.'));
insert into mnc(mcc,mnc,operator) values(362,76,trim('Antiliano Por N.V.'));
insert into mnc(mcc,mnc,operator) values(362,78,trim('Telefonia Bonairiano N.V.'));
insert into mnc(mcc,mnc,operator) values(362,91,trim('Liberty Latin America'));
insert into mnc(mcc,mnc,operator) values(362,94,trim('Bòbò Frus N.V.'));
insert into mnc(mcc,mnc,operator) values(362,95,trim('E.O.C.G. Wireless'));
insert into mnc(mcc,mnc,operator) values(310,110,trim('PTI Pacifica Inc.'));
insert into mnc(mcc,mnc,operator) values(310,370,trim('NTT DoCoMo Pacific'));
insert into mnc(mcc,mnc,operator) values(310,17,trim('North Sight Communications Inc.'));
insert into mnc(mcc,mnc,operator) values(310,260,trim('T Mobile US'));
insert into mnc(mcc,mnc,operator) values(310,280,trim('ATandT Mobility'));
insert into mnc(mcc,mnc,operator) values(313,510,trim('Puerto Rico Telecom Company'));
insert into mnc(mcc,mnc,operator) values(313,790,trim('Liberty Cablevision of Puerto Rico LLC'));
insert into mnc(mcc,mnc,operator) values(330,0,trim('PR Wireless'));
insert into mnc(mcc,mnc,operator) values(330,110,trim('América Móvil'));
insert into mnc(mcc,mnc,operator) values(330,120,trim('PR Wireless'));
insert into mnc(mcc,mnc,operator) values(356,50,trim('Wireless Ventures St Kitts-Nevis Limited'));
insert into mnc(mcc,mnc,operator) values(356,70,trim('UTS'));
insert into mnc(mcc,mnc,operator) values(356,110,trim('Cable and Wireless St Kitts and Nevis Ltd'));
insert into mnc(mcc,mnc,operator) values(358,110,trim('Cable and Wireless'));
insert into mnc(mcc,mnc,operator) values(308,1,trim('St Pierre et Miquelon Télécom'));
insert into mnc(mcc,mnc,operator) values(308,2,trim('GLOBALTEL'));
insert into mnc(mcc,mnc,operator) values(308,3,trim('St Pierre et Miquelon Télécom'));
insert into mnc(mcc,mnc,operator) values(360,50,trim('Digicel St Vincent and the Grenadines Limited'));
insert into mnc(mcc,mnc,operator) values(360,100,trim(''));
insert into mnc(mcc,mnc,operator) values(360,110,trim('Cable and Wireless St Vincent and the Grenadines Ltd'));
insert into mnc(mcc,mnc,operator) values(374,1,trim('TSTT'));
insert into mnc(mcc,mnc,operator) values(374,12,trim('TSTT'));
insert into mnc(mcc,mnc,operator) values(374,13,trim('Digicel Trinidad and Tobago Limited'));
insert into mnc(mcc,mnc,operator) values(374,20,trim('TSTT'));
insert into mnc(mcc,mnc,operator) values(374,120,trim('TSTT'));
insert into mnc(mcc,mnc,operator) values(374,129,trim('TSTT'));
insert into mnc(mcc,mnc,operator) values(374,130,trim('Digicel Trinidad and Tobago Limited'));
insert into mnc(mcc,mnc,operator) values(374,140,trim('LaqTel Ltd.'));
insert into mnc(mcc,mnc,operator) values(338,50,trim('Digicel Turks and Caicos Limited'));
insert into mnc(mcc,mnc,operator) values(376,350,trim('Cable and Wireless West Indies Ltd Turks and Caicos'));
insert into mnc(mcc,mnc,operator) values(376,351,trim('Digicel Turks and Caicos Limited'));
insert into mnc(mcc,mnc,operator) values(376,352,trim('Cable and Wireless West Indies Ltd Turks and Caicos'));
insert into mnc(mcc,mnc,operator) values(376,360,trim('Digicel Turks and Caicos Limited'));
insert into mnc(mcc,mnc,operator) values(310,4,trim('Verizon Wireless'));
insert into mnc(mcc,mnc,operator) values(310,5,trim('Verizon Wireless'));
insert into mnc(mcc,mnc,operator) values(310,6,trim('Verizon Wireless'));
insert into mnc(mcc,mnc,operator) values(310,10,trim('Verizon Wireless'));
insert into mnc(mcc,mnc,operator) values(310,12,trim('Verizon Wireless'));
insert into mnc(mcc,mnc,operator) values(310,13,trim('Verizon Wireless'));
insert into mnc(mcc,mnc,operator) values(310,14,trim(''));
insert into mnc(mcc,mnc,operator) values(310,15,trim('Southern Communications'));
insert into mnc(mcc,mnc,operator) values(310,16,trim('ATandT Mobility'));
insert into mnc(mcc,mnc,operator) values(310,20,trim('Union Telephone Company'));
insert into mnc(mcc,mnc,operator) values(310,30,trim('ATandT Mobility'));
insert into mnc(mcc,mnc,operator) values(310,34,trim('Airpeak'));
insert into mnc(mcc,mnc,operator) values(310,35,trim('ETEX Communications, LP'));
insert into mnc(mcc,mnc,operator) values(310,40,trim('Mobi, Inc.'));
insert into mnc(mcc,mnc,operator) values(310,50,trim('Alaska Communications'));
insert into mnc(mcc,mnc,operator) values(310,53,trim('T-Mobile US'));
insert into mnc(mcc,mnc,operator) values(310,54,trim('Alltel US'));
insert into mnc(mcc,mnc,operator) values(310,60,trim('Consolidated Telcom'));
insert into mnc(mcc,mnc,operator) values(310,66,trim('U.S. Cellular'));
insert into mnc(mcc,mnc,operator) values(310,70,trim('ATandT Mobility'));
insert into mnc(mcc,mnc,operator) values(310,80,trim('ATandT Mobility'));
insert into mnc(mcc,mnc,operator) values(310,90,trim('ATandT Mobility'));
insert into mnc(mcc,mnc,operator) values(310,100,trim('New Mexico RSA 4 East LP'));
insert into mnc(mcc,mnc,operator) values(310,120,trim('T-Mobile US'));
insert into mnc(mcc,mnc,operator) values(310,130,trim('Carolina West Wireless'));
insert into mnc(mcc,mnc,operator) values(310,140,trim('Teleguam Holdings LLC'));
insert into mnc(mcc,mnc,operator) values(310,150,trim('ATandT Mobility'));
insert into mnc(mcc,mnc,operator) values(310,160,trim('T-Mobile US'));
insert into mnc(mcc,mnc,operator) values(310,170,trim('ATandT Mobility'));
insert into mnc(mcc,mnc,operator) values(310,180,trim('West Central Wireless'));
insert into mnc(mcc,mnc,operator) values(310,190,trim('Alaska Communications'));
insert into mnc(mcc,mnc,operator) values(310,200,trim('T-Mobile'));
insert into mnc(mcc,mnc,operator) values(310,210,trim('T-Mobile'));
insert into mnc(mcc,mnc,operator) values(310,220,trim('T-Mobile'));
insert into mnc(mcc,mnc,operator) values(310,230,trim('T-Mobile'));
insert into mnc(mcc,mnc,operator) values(310,240,trim('T-Mobile'));
insert into mnc(mcc,mnc,operator) values(310,250,trim('T-Mobile'));
insert into mnc(mcc,mnc,operator) values(310,260,trim('T-Mobile US'));
insert into mnc(mcc,mnc,operator) values(310,270,trim('T-Mobile'));
insert into mnc(mcc,mnc,operator) values(310,290,trim('NEP Cellcorp Inc.'));
insert into mnc(mcc,mnc,operator) values(310,300,trim('iSmart Mobile, LLC'));
insert into mnc(mcc,mnc,operator) values(310,310,trim('T Mobile'));
insert into mnc(mcc,mnc,operator) values(310,311,trim('Farmers Wireless'));
insert into mnc(mcc,mnc,operator) values(310,320,trim('Smith Bagley, Inc.'));
insert into mnc(mcc,mnc,operator) values(310,330,trim('Wireless Partners, LLC'));
insert into mnc(mcc,mnc,operator) values(310,340,trim('Limitless Mobile, LLC'));
insert into mnc(mcc,mnc,operator) values(310,350,trim('Verizon Wireless'));
insert into mnc(mcc,mnc,operator) values(310,360,trim('Cellular Network Partnership'));
insert into mnc(mcc,mnc,operator) values(310,380,trim('ATandT Mobility'));
insert into mnc(mcc,mnc,operator) values(310,390,trim('TX 11 Acquisition, LLC'));
insert into mnc(mcc,mnc,operator) values(310,400,trim('ITandE Overseas, Inc'));
insert into mnc(mcc,mnc,operator) values(310,410,trim('ATandT Mobility'));
insert into mnc(mcc,mnc,operator) values(310,420,trim('World Mobile Networks, LLC'));
insert into mnc(mcc,mnc,operator) values(310,430,trim('GCI Communications Corp.'));
insert into mnc(mcc,mnc,operator) values(310,440,trim('Numerex'));
insert into mnc(mcc,mnc,operator) values(310,450,trim('Viaero Wireless'));
insert into mnc(mcc,mnc,operator) values(310,460,trim('Eseye'));
insert into mnc(mcc,mnc,operator) values(310,490,trim('T Mobile'));
insert into mnc(mcc,mnc,operator) values(310,500,trim('Public Service Cellular Inc.'));
insert into mnc(mcc,mnc,operator) values(310,510,trim('Nsight'));
insert into mnc(mcc,mnc,operator) values(310,520,trim('Transaction Network Services'));
insert into mnc(mcc,mnc,operator) values(310,530,trim('T Mobile'));
insert into mnc(mcc,mnc,operator) values(310,540,trim('Hilliary Communications'));
insert into mnc(mcc,mnc,operator) values(310,550,trim('Syniverse Technologies'));
insert into mnc(mcc,mnc,operator) values(310,560,trim('ATandT Mobility'));
insert into mnc(mcc,mnc,operator) values(310,570,trim('Broadpoint, LLC'));
insert into mnc(mcc,mnc,operator) values(310,580,trim('Inland Cellular Telephone Company'));
insert into mnc(mcc,mnc,operator) values(310,590,trim('Verizon Wireless'));
insert into mnc(mcc,mnc,operator) values(310,591,trim('Verizon Wireless'));
insert into mnc(mcc,mnc,operator) values(310,592,trim('Verizon Wireless'));
insert into mnc(mcc,mnc,operator) values(310,593,trim('Verizon Wireless'));
insert into mnc(mcc,mnc,operator) values(310,594,trim('Verizon Wireless'));
insert into mnc(mcc,mnc,operator) values(310,595,trim('Verizon Wireless'));
insert into mnc(mcc,mnc,operator) values(310,596,trim('Verizon Wireless'));
insert into mnc(mcc,mnc,operator) values(310,597,trim('Verizon Wireless'));
insert into mnc(mcc,mnc,operator) values(310,598,trim('Verizon Wireless'));
insert into mnc(mcc,mnc,operator) values(310,599,trim('Verizon Wireless'));
insert into mnc(mcc,mnc,operator) values(310,600,trim('NewCell Inc.'));
insert into mnc(mcc,mnc,operator) values(310,610,trim('Mavenir Systems Inc'));
insert into mnc(mcc,mnc,operator) values(310,620,trim('Nsighttel Wireless LLC'));
insert into mnc(mcc,mnc,operator) values(310,630,trim('Commnet Wireless LLC'));
insert into mnc(mcc,mnc,operator) values(310,640,trim('Numerex'));
insert into mnc(mcc,mnc,operator) values(310,650,trim('Jasper Technologies'));
insert into mnc(mcc,mnc,operator) values(310,660,trim(''));
insert into mnc(mcc,mnc,operator) values(310,670,trim('ATandT Mobility'));
insert into mnc(mcc,mnc,operator) values(310,680,trim('ATandT Mobility'));
insert into mnc(mcc,mnc,operator) values(310,690,trim('Limitless Mobile, LLC'));
insert into mnc(mcc,mnc,operator) values(310,700,trim('Cross Valiant Cellular Partnership'));
insert into mnc(mcc,mnc,operator) values(310,710,trim('Arctic Slope Telephone Association Cooperative'));
insert into mnc(mcc,mnc,operator) values(310,720,trim('Syniverse Technologies'));
insert into mnc(mcc,mnc,operator) values(310,730,trim('U.S. Cellular'));
insert into mnc(mcc,mnc,operator) values(310,740,trim('Viaero Wireless'));
insert into mnc(mcc,mnc,operator) values(310,750,trim('East Kentucky Network, LLC'));
insert into mnc(mcc,mnc,operator) values(310,760,trim('Lynch 3G Communications Corporation'));
insert into mnc(mcc,mnc,operator) values(310,770,trim('T-Mobile'));
insert into mnc(mcc,mnc,operator) values(310,780,trim('D. D. Inc.'));
insert into mnc(mcc,mnc,operator) values(310,790,trim('PinPoint Communications Inc.'));
insert into mnc(mcc,mnc,operator) values(310,800,trim('T-Mobile'));
insert into mnc(mcc,mnc,operator) values(310,810,trim('Pacific Lightwave Inc.'));
insert into mnc(mcc,mnc,operator) values(310,820,trim('Verizon Wireless'));
insert into mnc(mcc,mnc,operator) values(310,830,trim('T-Mobile US'));
insert into mnc(mcc,mnc,operator) values(310,840,trim('Telecom North America Mobile, Inc.'));
insert into mnc(mcc,mnc,operator) values(310,850,trim('Aeris Communications, Inc.'));
insert into mnc(mcc,mnc,operator) values(310,860,trim('TX RSA 15B2, LP'));
insert into mnc(mcc,mnc,operator) values(310,870,trim('Kaplan Telephone Company'));
insert into mnc(mcc,mnc,operator) values(310,880,trim('Advantage Cellular Systems, Inc.'));
insert into mnc(mcc,mnc,operator) values(310,890,trim('Verizon Wireless'));
insert into mnc(mcc,mnc,operator) values(310,891,trim('Verizon Wireless'));
insert into mnc(mcc,mnc,operator) values(310,892,trim('Verizon Wireless'));
insert into mnc(mcc,mnc,operator) values(310,893,trim('Verizon Wireless'));
insert into mnc(mcc,mnc,operator) values(310,894,trim('Verizon Wireless'));
insert into mnc(mcc,mnc,operator) values(310,895,trim('Verizon Wireless'));
insert into mnc(mcc,mnc,operator) values(310,896,trim('Verizon Wireless'));
insert into mnc(mcc,mnc,operator) values(310,897,trim('Verizon Wireless'));
insert into mnc(mcc,mnc,operator) values(310,898,trim('Verizon Wireless'));
insert into mnc(mcc,mnc,operator) values(310,899,trim('Verizon Wireless'));
insert into mnc(mcc,mnc,operator) values(310,900,trim('Cable and Communications Corporation'));
insert into mnc(mcc,mnc,operator) values(310,910,trim('Verizon Wireless'));
insert into mnc(mcc,mnc,operator) values(310,920,trim('James Valley Wireless, LLC'));
insert into mnc(mcc,mnc,operator) values(310,930,trim('Copper Valley Wireless'));
insert into mnc(mcc,mnc,operator) values(310,940,trim('Tyntec Inc.'));
insert into mnc(mcc,mnc,operator) values(310,950,trim('ATandT Mobility'));
insert into mnc(mcc,mnc,operator) values(310,960,trim('UBET Wireless'));
insert into mnc(mcc,mnc,operator) values(310,970,trim('Globalstar'));
insert into mnc(mcc,mnc,operator) values(310,980,trim('Texas RSA 7B3'));
insert into mnc(mcc,mnc,operator) values(310,990,trim('Evolve Cellular Inc.'));
insert into mnc(mcc,mnc,operator) values(311,0,trim('Mid-Tex Cellular Ltd.'));
insert into mnc(mcc,mnc,operator) values(311,10,trim('Chariton Valley Communications'));
insert into mnc(mcc,mnc,operator) values(311,12,trim('Verizon Wireless'));
insert into mnc(mcc,mnc,operator) values(311,20,trim('Missouri RSA 5 Partnership'));
insert into mnc(mcc,mnc,operator) values(311,30,trim('Americell PA 3 Partnership'));
insert into mnc(mcc,mnc,operator) values(311,40,trim('Commnet Wireless'));
insert into mnc(mcc,mnc,operator) values(311,50,trim('Thumb Cellular LP'));
insert into mnc(mcc,mnc,operator) values(311,60,trim('Space Data Corporation'));
insert into mnc(mcc,mnc,operator) values(311,70,trim('ATandT Mobility'));
insert into mnc(mcc,mnc,operator) values(311,80,trim('Pine Telephone Company'));
insert into mnc(mcc,mnc,operator) values(311,90,trim('ATandT Mobility'));
insert into mnc(mcc,mnc,operator) values(311,100,trim('Nex-Tech Wireless'));
insert into mnc(mcc,mnc,operator) values(311,110,trim('Verizon Wireless'));
insert into mnc(mcc,mnc,operator) values(311,130,trim('Black and Veatch'));
insert into mnc(mcc,mnc,operator) values(311,140,trim('Cross Telephone Company'));
insert into mnc(mcc,mnc,operator) values(311,150,trim('Wilkes Cellular'));
insert into mnc(mcc,mnc,operator) values(311,160,trim('Lightsquared L.P.'));
insert into mnc(mcc,mnc,operator) values(311,170,trim('Tampnet'));
insert into mnc(mcc,mnc,operator) values(311,180,trim('ATandT Mobility'));
insert into mnc(mcc,mnc,operator) values(311,190,trim('ATandT Mobility'));
insert into mnc(mcc,mnc,operator) values(311,200,trim('Dish Wireless'));
insert into mnc(mcc,mnc,operator) values(311,210,trim('Telnyx LLC'));
insert into mnc(mcc,mnc,operator) values(311,220,trim('U.S. Cellular'));
insert into mnc(mcc,mnc,operator) values(311,225,trim('U.S. Cellular'));
insert into mnc(mcc,mnc,operator) values(311,228,trim('U.S. Cellular'));
insert into mnc(mcc,mnc,operator) values(311,229,trim('U.S. Cellular'));
insert into mnc(mcc,mnc,operator) values(311,230,trim('Cellular South Inc.'));
insert into mnc(mcc,mnc,operator) values(311,240,trim('Cordova Wireless'));
insert into mnc(mcc,mnc,operator) values(311,250,trim('ITandE Overseas, Inc'));
insert into mnc(mcc,mnc,operator) values(311,260,trim('T-Mobile US'));
insert into mnc(mcc,mnc,operator) values(311,270,trim('Verizon Wireless'));
insert into mnc(mcc,mnc,operator) values(311,271,trim('Verizon Wireless'));
insert into mnc(mcc,mnc,operator) values(311,272,trim('Verizon Wireless'));
insert into mnc(mcc,mnc,operator) values(311,273,trim('Verizon Wireless'));
insert into mnc(mcc,mnc,operator) values(311,274,trim('Verizon Wireless'));
insert into mnc(mcc,mnc,operator) values(311,275,trim('Verizon Wireless'));
insert into mnc(mcc,mnc,operator) values(311,276,trim('Verizon Wireless'));
insert into mnc(mcc,mnc,operator) values(311,277,trim('Verizon Wireless'));
insert into mnc(mcc,mnc,operator) values(311,278,trim('Verizon Wireless'));
insert into mnc(mcc,mnc,operator) values(311,279,trim('Verizon Wireless'));
insert into mnc(mcc,mnc,operator) values(311,280,trim('Verizon Wireless'));
insert into mnc(mcc,mnc,operator) values(311,281,trim('Verizon Wireless'));
insert into mnc(mcc,mnc,operator) values(311,282,trim('Verizon Wireless'));
insert into mnc(mcc,mnc,operator) values(311,283,trim('Verizon Wireless'));
insert into mnc(mcc,mnc,operator) values(311,284,trim('Verizon Wireless'));
insert into mnc(mcc,mnc,operator) values(311,285,trim('Verizon Wireless'));
insert into mnc(mcc,mnc,operator) values(311,286,trim('Verizon Wireless'));
insert into mnc(mcc,mnc,operator) values(311,287,trim('Verizon Wireless'));
insert into mnc(mcc,mnc,operator) values(311,288,trim('Verizon Wireless'));
insert into mnc(mcc,mnc,operator) values(311,289,trim('Verizon Wireless'));
insert into mnc(mcc,mnc,operator) values(311,290,trim('PinPoint Communications Inc.'));
insert into mnc(mcc,mnc,operator) values(311,300,trim('Nexus Communications, Inc.'));
insert into mnc(mcc,mnc,operator) values(311,310,trim('Leaco Rural Telephone Company Inc.'));
insert into mnc(mcc,mnc,operator) values(311,320,trim('Commnet Wireless'));
insert into mnc(mcc,mnc,operator) values(311,330,trim('Bug Tussel Wireless LLC'));
insert into mnc(mcc,mnc,operator) values(311,340,trim('Illinois Valley Cellular'));
insert into mnc(mcc,mnc,operator) values(311,350,trim('Sagebrush Cellular, Inc.'));
insert into mnc(mcc,mnc,operator) values(311,360,trim('Stelera Wireless'));
insert into mnc(mcc,mnc,operator) values(311,370,trim('General Communication Inc.'));
insert into mnc(mcc,mnc,operator) values(311,380,trim('New Dimension Wireless Ltd.'));
insert into mnc(mcc,mnc,operator) values(311,390,trim('Verizon Wireless'));
insert into mnc(mcc,mnc,operator) values(311,400,trim(''));
insert into mnc(mcc,mnc,operator) values(311,410,trim('Iowa RSA No. 2 LP'));
insert into mnc(mcc,mnc,operator) values(311,420,trim('Northwest Missouri Cellular LP'));
insert into mnc(mcc,mnc,operator) values(311,430,trim('RSA 1 LP'));
insert into mnc(mcc,mnc,operator) values(311,440,trim('Verizon Wireless'));
insert into mnc(mcc,mnc,operator) values(311,450,trim('Panhandle Telecommunication Systems Inc.'));
insert into mnc(mcc,mnc,operator) values(311,460,trim('Electric Imp Inc.'));
insert into mnc(mcc,mnc,operator) values(311,470,trim('Vitelcom Cellular Inc.'));
insert into mnc(mcc,mnc,operator) values(311,480,trim('Verizon Wireless'));
insert into mnc(mcc,mnc,operator) values(311,481,trim('Verizon Wireless'));
insert into mnc(mcc,mnc,operator) values(311,482,trim('Verizon Wireless'));
insert into mnc(mcc,mnc,operator) values(311,483,trim('Verizon Wireless'));
insert into mnc(mcc,mnc,operator) values(311,484,trim('Verizon Wireless'));
insert into mnc(mcc,mnc,operator) values(311,485,trim('Verizon Wireless'));
insert into mnc(mcc,mnc,operator) values(311,486,trim('Verizon Wireless'));
insert into mnc(mcc,mnc,operator) values(311,487,trim('Verizon Wireless'));
insert into mnc(mcc,mnc,operator) values(311,488,trim('Verizon Wireless'));
insert into mnc(mcc,mnc,operator) values(311,489,trim('Verizon Wireless'));
insert into mnc(mcc,mnc,operator) values(311,490,trim('T-Mobile US'));
insert into mnc(mcc,mnc,operator) values(311,500,trim('Mobi, Inc.'));
insert into mnc(mcc,mnc,operator) values(311,510,trim('Ligado Networks'));
insert into mnc(mcc,mnc,operator) values(311,520,trim('Lightsquared L.P.'));
insert into mnc(mcc,mnc,operator) values(311,530,trim('WorldCell Solutions LLC'));
insert into mnc(mcc,mnc,operator) values(311,540,trim('Coeur Rochester, Inc'));
insert into mnc(mcc,mnc,operator) values(311,550,trim('Commnet Wireless LLC'));
insert into mnc(mcc,mnc,operator) values(311,560,trim('OTZ Communications, Inc.'));
insert into mnc(mcc,mnc,operator) values(311,570,trim('Mediacom'));
insert into mnc(mcc,mnc,operator) values(311,580,trim('U.S. Cellular'));
insert into mnc(mcc,mnc,operator) values(311,588,trim('U.S. Cellular'));
insert into mnc(mcc,mnc,operator) values(311,589,trim('U.S. Cellular'));
insert into mnc(mcc,mnc,operator) values(311,590,trim('Verizon Wireless'));
insert into mnc(mcc,mnc,operator) values(311,600,trim('Limitless Mobile, LLC'));
insert into mnc(mcc,mnc,operator) values(311,610,trim('North Dakota Network Co.'));
insert into mnc(mcc,mnc,operator) values(311,620,trim('TerreStar Networks, Inc.'));
insert into mnc(mcc,mnc,operator) values(311,630,trim('Cellular South Inc.'));
insert into mnc(mcc,mnc,operator) values(311,640,trim('Standing Rock Telecommunications'));
insert into mnc(mcc,mnc,operator) values(311,650,trim('United Wireless'));
insert into mnc(mcc,mnc,operator) values(311,660,trim('Metro by T-Mobile'));
insert into mnc(mcc,mnc,operator) values(311,670,trim('Pine Belt Cellular Inc.'));
insert into mnc(mcc,mnc,operator) values(311,680,trim('GreenFly LLC'));
insert into mnc(mcc,mnc,operator) values(311,690,trim('TeleBEEPER of New Mexico'));
insert into mnc(mcc,mnc,operator) values(311,700,trim('Midwest Network Solutions Hub LLC'));
insert into mnc(mcc,mnc,operator) values(311,710,trim('Northeast Wireless Networks LLC'));
insert into mnc(mcc,mnc,operator) values(311,720,trim('MainePCS LLC'));
insert into mnc(mcc,mnc,operator) values(311,730,trim('Proximiti Mobility Inc.'));
insert into mnc(mcc,mnc,operator) values(311,740,trim('Telalaska Cellular'));
insert into mnc(mcc,mnc,operator) values(311,750,trim('Flat Wireless LLC'));
insert into mnc(mcc,mnc,operator) values(311,760,trim('Edigen Inc.'));
insert into mnc(mcc,mnc,operator) values(311,770,trim('Altiostar Networks, Inc.'));
insert into mnc(mcc,mnc,operator) values(311,780,trim('American Samoa Telecommunications Authority'));
insert into mnc(mcc,mnc,operator) values(311,790,trim('Coleman County Telephone Cooperative, Inc.'));
insert into mnc(mcc,mnc,operator) values(311,800,trim('Verizon Wireless'));
insert into mnc(mcc,mnc,operator) values(311,810,trim('Verizon Wireless'));
insert into mnc(mcc,mnc,operator) values(311,820,trim('Ribbon Communications'));
insert into mnc(mcc,mnc,operator) values(311,830,trim('Thumb Cellular LP'));
insert into mnc(mcc,mnc,operator) values(311,840,trim('Nsight'));
insert into mnc(mcc,mnc,operator) values(311,850,trim('Nsight'));
insert into mnc(mcc,mnc,operator) values(311,860,trim('Uintah Basin Electronic Telecommunications'));
insert into mnc(mcc,mnc,operator) values(311,870,trim('T-Mobile US'));
insert into mnc(mcc,mnc,operator) values(311,880,trim('T-Mobile US'));
insert into mnc(mcc,mnc,operator) values(311,882,trim('T-Mobile US'));
insert into mnc(mcc,mnc,operator) values(311,890,trim('Globecomm Network Services Corporation'));
insert into mnc(mcc,mnc,operator) values(311,900,trim('GigSky'));
insert into mnc(mcc,mnc,operator) values(311,910,trim('SI Wireless LLC'));
insert into mnc(mcc,mnc,operator) values(311,920,trim('Missouri RSA 5 Partnership'));
insert into mnc(mcc,mnc,operator) values(311,930,trim('Cox Communications'));
insert into mnc(mcc,mnc,operator) values(311,940,trim('T-Mobile US'));
insert into mnc(mcc,mnc,operator) values(311,950,trim('Enhanced Telecommmunications Corp.'));
insert into mnc(mcc,mnc,operator) values(311,960,trim('Lycamobile USA Inc.'));
insert into mnc(mcc,mnc,operator) values(311,970,trim('Big River Broadband, LLC'));
insert into mnc(mcc,mnc,operator) values(311,980,trim('LigTel Communications'));
insert into mnc(mcc,mnc,operator) values(311,990,trim('VTel Wireless'));
insert into mnc(mcc,mnc,operator) values(312,10,trim('Chariton Valley Communications Corporation, Inc'));
insert into mnc(mcc,mnc,operator) values(312,20,trim('Infrastructure Networks, LLC'));
insert into mnc(mcc,mnc,operator) values(312,30,trim('Cross Wireless'));
insert into mnc(mcc,mnc,operator) values(312,40,trim('Custer Telephone Co-op (CTCI)'));
insert into mnc(mcc,mnc,operator) values(312,50,trim('Fuego Wireless'));
insert into mnc(mcc,mnc,operator) values(312,60,trim('CoverageCo'));
insert into mnc(mcc,mnc,operator) values(312,70,trim('Adams Networks Inc'));
insert into mnc(mcc,mnc,operator) values(312,80,trim('South Georgia Regional Information Technology Authority'));
insert into mnc(mcc,mnc,operator) values(312,90,trim('ATandT Mobility'));
insert into mnc(mcc,mnc,operator) values(312,100,trim('ClearSky Technologies, Inc.'));
insert into mnc(mcc,mnc,operator) values(312,110,trim('Texas Energy Network LLC'));
insert into mnc(mcc,mnc,operator) values(312,120,trim('East Kentucky Network, LLC'));
insert into mnc(mcc,mnc,operator) values(312,130,trim('East Kentucky Network, LLC'));
insert into mnc(mcc,mnc,operator) values(312,140,trim('Cleveland Unlimited, Inc.'));
insert into mnc(mcc,mnc,operator) values(312,150,trim('Northwest Missouri Cellular LP'));
insert into mnc(mcc,mnc,operator) values(312,160,trim('RSA1 Limited Partnership'));
insert into mnc(mcc,mnc,operator) values(312,170,trim('Iowa RSA No. 2 LP'));
insert into mnc(mcc,mnc,operator) values(312,180,trim('Limitless Mobile LLC'));
insert into mnc(mcc,mnc,operator) values(312,190,trim('T-Mobile US'));
insert into mnc(mcc,mnc,operator) values(312,200,trim('Voyager Mobility LLC'));
insert into mnc(mcc,mnc,operator) values(312,210,trim('Aspenta International, Inc.'));
insert into mnc(mcc,mnc,operator) values(312,220,trim('Chariton Valley Communications Corporation, Inc.'));
insert into mnc(mcc,mnc,operator) values(312,230,trim('North Dakota Network Co.'));
insert into mnc(mcc,mnc,operator) values(312,240,trim('Sprint Corporation'));
insert into mnc(mcc,mnc,operator) values(312,250,trim('T-Mobile US'));
insert into mnc(mcc,mnc,operator) values(312,260,trim('WorldCell Solutions LLC'));
insert into mnc(mcc,mnc,operator) values(312,270,trim('Cellular Network Partnership'));
insert into mnc(mcc,mnc,operator) values(312,280,trim('Cellular Network Partnership'));
insert into mnc(mcc,mnc,operator) values(312,290,trim('Uintah Basin Electronic Telecommunications'));
insert into mnc(mcc,mnc,operator) values(312,300,trim('Telecom North America Mobile, Inc.'));
insert into mnc(mcc,mnc,operator) values(312,310,trim('Clear Stream Communications, LLC'));
insert into mnc(mcc,mnc,operator) values(312,320,trim('RTC Communications LLC'));
insert into mnc(mcc,mnc,operator) values(312,330,trim('Nemont Communications, Inc.'));
insert into mnc(mcc,mnc,operator) values(312,340,trim('Matanuska Telephone Association, Inc.'));
insert into mnc(mcc,mnc,operator) values(312,350,trim('Triangle Communication System Inc.'));
insert into mnc(mcc,mnc,operator) values(312,360,trim('Wes-Tex Telecommunications, Ltd.'));
insert into mnc(mcc,mnc,operator) values(312,370,trim('Commnet Wireless'));
insert into mnc(mcc,mnc,operator) values(312,380,trim('Copper Valley Wireless'));
insert into mnc(mcc,mnc,operator) values(312,390,trim('FTC Communications LLC'));
insert into mnc(mcc,mnc,operator) values(312,400,trim('Mid-Rivers Telephone Cooperative'));
insert into mnc(mcc,mnc,operator) values(312,410,trim('Eltopia Communications, LLC'));
insert into mnc(mcc,mnc,operator) values(312,420,trim('Nex-Tech Wireless'));
insert into mnc(mcc,mnc,operator) values(312,430,trim('Silver Star Communications'));
insert into mnc(mcc,mnc,operator) values(312,440,trim('Kajeet, Inc.'));
insert into mnc(mcc,mnc,operator) values(312,450,trim('Cable and Communications Corporation'));
insert into mnc(mcc,mnc,operator) values(312,460,trim('Ketchikan Public Utilities KPU'));
insert into mnc(mcc,mnc,operator) values(312,470,trim('Carolina West Wireless'));
insert into mnc(mcc,mnc,operator) values(312,480,trim('Sagebrush Cellular, Inc.'));
insert into mnc(mcc,mnc,operator) values(312,490,trim('TrustComm, Inc.'));
insert into mnc(mcc,mnc,operator) values(312,500,trim('AB Spectrum LLC'));
insert into mnc(mcc,mnc,operator) values(312,510,trim('WUE Inc.'));
insert into mnc(mcc,mnc,operator) values(312,520,trim('ANIN'));
insert into mnc(mcc,mnc,operator) values(312,530,trim('T-Mobile US'));
insert into mnc(mcc,mnc,operator) values(312,540,trim('Broadband In Hand LLC'));
insert into mnc(mcc,mnc,operator) values(312,550,trim('Great Plains Communications, Inc.'));
insert into mnc(mcc,mnc,operator) values(312,560,trim('NHLT Inc.'));
insert into mnc(mcc,mnc,operator) values(312,570,trim('Buffalo-Lake Erie Wireless Systems Co LLC'));
insert into mnc(mcc,mnc,operator) values(312,580,trim('Google LLC'));
insert into mnc(mcc,mnc,operator) values(312,590,trim('Northern Michigan University'));
insert into mnc(mcc,mnc,operator) values(312,600,trim('Sagebrush Cellular, Inc.'));
insert into mnc(mcc,mnc,operator) values(312,610,trim('ShawnTech Communications'));
insert into mnc(mcc,mnc,operator) values(312,620,trim('GlobeTouch Inc.'));
insert into mnc(mcc,mnc,operator) values(312,630,trim('NetGenuity, Inc.'));
insert into mnc(mcc,mnc,operator) values(312,640,trim('Sagebrush Cellular, Inc.'));
insert into mnc(mcc,mnc,operator) values(312,650,trim('Brightlink'));
insert into mnc(mcc,mnc,operator) values(312,660,trim('nTelos Wireless'));
insert into mnc(mcc,mnc,operator) values(312,670,trim('ATandT Mobility'));
insert into mnc(mcc,mnc,operator) values(312,680,trim('ATandT Mobility'));
insert into mnc(mcc,mnc,operator) values(312,690,trim('TGS, LLC'));
insert into mnc(mcc,mnc,operator) values(312,700,trim('Wireless Partners, LLC'));
insert into mnc(mcc,mnc,operator) values(312,710,trim('Great North Woods Wireless LLC'));
insert into mnc(mcc,mnc,operator) values(312,720,trim('Southern Communications Services'));
insert into mnc(mcc,mnc,operator) values(312,730,trim('Triangle Communication System Inc.'));
insert into mnc(mcc,mnc,operator) values(312,740,trim('KDDI America, Inc.'));
insert into mnc(mcc,mnc,operator) values(312,750,trim('Artemis Networks LLC'));
insert into mnc(mcc,mnc,operator) values(312,760,trim('Arctic Slope Telephone Association Cooperative'));
insert into mnc(mcc,mnc,operator) values(312,770,trim('Verizon Wireless'));
insert into mnc(mcc,mnc,operator) values(312,780,trim('Redzone Wireless'));
insert into mnc(mcc,mnc,operator) values(312,790,trim('Gila Electronics'));
insert into mnc(mcc,mnc,operator) values(312,800,trim('Cirrus Core Networks'));
insert into mnc(mcc,mnc,operator) values(312,810,trim('Bristol Bay Telephone Cooperative'));
insert into mnc(mcc,mnc,operator) values(312,820,trim('Santel Communications Cooperative, Inc.'));
insert into mnc(mcc,mnc,operator) values(312,830,trim('Kings County Office of Education'));
insert into mnc(mcc,mnc,operator) values(312,840,trim('South Georgia Regional Information Technology Authority'));
insert into mnc(mcc,mnc,operator) values(312,850,trim('Onvoy Spectrum LLC'));
insert into mnc(mcc,mnc,operator) values(312,860,trim('Flat Wireless LLC'));
insert into mnc(mcc,mnc,operator) values(312,870,trim('GigSky Mobile LLC'));
insert into mnc(mcc,mnc,operator) values(312,880,trim('Albemarle County Public Schools'));
insert into mnc(mcc,mnc,operator) values(312,890,trim('Circle Gx'));
insert into mnc(mcc,mnc,operator) values(312,900,trim('Flat West Wireless LLC'));
insert into mnc(mcc,mnc,operator) values(312,910,trim('East Kentucky Network LLC'));
insert into mnc(mcc,mnc,operator) values(312,920,trim('Northeast Wireless Networks LLC'));
insert into mnc(mcc,mnc,operator) values(312,930,trim('Hewlett-Packard Communication Services LLC'));
insert into mnc(mcc,mnc,operator) values(312,940,trim('Webformix'));
insert into mnc(mcc,mnc,operator) values(312,950,trim('Custer Telephone Co-op CTCI'));
insert into mnc(mcc,mnc,operator) values(312,960,trim('MandA Technology, Inc.'));
insert into mnc(mcc,mnc,operator) values(312,970,trim('IOSAZ Intellectual Property LLC'));
insert into mnc(mcc,mnc,operator) values(312,980,trim('Mark Twain Communications Company'));
insert into mnc(mcc,mnc,operator) values(312,990,trim('Premier Holdings LLC'));
insert into mnc(mcc,mnc,operator) values(313,0,trim('Tennessee Wireless'));
insert into mnc(mcc,mnc,operator) values(313,10,trim('Cross Wireless LLC'));
insert into mnc(mcc,mnc,operator) values(313,20,trim('Cambridge Telephone Company Inc.'));
insert into mnc(mcc,mnc,operator) values(313,30,trim('ATandT Mobility'));
insert into mnc(mcc,mnc,operator) values(313,40,trim('Nucla-Naturita Telephone Company'));
insert into mnc(mcc,mnc,operator) values(313,50,trim('Manti Tele Communications Company, Inc.'));
insert into mnc(mcc,mnc,operator) values(313,60,trim('Country Wireless'));
insert into mnc(mcc,mnc,operator) values(313,61,trim('Country Wireless'));
insert into mnc(mcc,mnc,operator) values(313,70,trim('Midwest Network Solutions Hub LLC'));
insert into mnc(mcc,mnc,operator) values(313,80,trim('Speedwavz LLP'));
insert into mnc(mcc,mnc,operator) values(313,90,trim('Vivint Wireless, Inc.'));
insert into mnc(mcc,mnc,operator) values(313,100,trim('ATandT FirstNet'));
insert into mnc(mcc,mnc,operator) values(313,110,trim('ATandT FirstNet'));
insert into mnc(mcc,mnc,operator) values(313,120,trim('ATandT FirstNet'));
insert into mnc(mcc,mnc,operator) values(313,130,trim('ATandT FirstNet'));
insert into mnc(mcc,mnc,operator) values(313,140,trim('ATandT FirstNet'));
insert into mnc(mcc,mnc,operator) values(313,150,trim('700 MHz Public Safety Broadband'));
insert into mnc(mcc,mnc,operator) values(313,160,trim('700 MHz Public Safety Broadband'));
insert into mnc(mcc,mnc,operator) values(313,170,trim('700 MHz Public Safety Broadband'));
insert into mnc(mcc,mnc,operator) values(313,180,trim('700 MHz Public Safety Broadband'));
insert into mnc(mcc,mnc,operator) values(313,190,trim('700 MHz Public Safety Broadband'));
insert into mnc(mcc,mnc,operator) values(313,200,trim('Mercury Network Corporation'));
insert into mnc(mcc,mnc,operator) values(313,210,trim('ATandT Mobility'));
insert into mnc(mcc,mnc,operator) values(313,220,trim('Custer Telephone Co-op CTCI'));
insert into mnc(mcc,mnc,operator) values(313,230,trim('Velocity Communications Inc.'));
insert into mnc(mcc,mnc,operator) values(313,240,trim('Fundamental Holdings, Corp.'));
insert into mnc(mcc,mnc,operator) values(313,250,trim('Imperial County Office of Education'));
insert into mnc(mcc,mnc,operator) values(313,260,trim('Expeto Wireless Inc.'));
insert into mnc(mcc,mnc,operator) values(313,270,trim('Blackstar Management'));
insert into mnc(mcc,mnc,operator) values(313,280,trim('King Street Wireless LP'));
insert into mnc(mcc,mnc,operator) values(313,290,trim('Gulf Coast Broadband LLC'));
insert into mnc(mcc,mnc,operator) values(313,300,trim('Southern California Edison'));
insert into mnc(mcc,mnc,operator) values(313,310,trim('CAL.NET Inc.'));
insert into mnc(mcc,mnc,operator) values(313,320,trim('Paladin Wireless'));
insert into mnc(mcc,mnc,operator) values(313,330,trim('CenturyTel Broadband Services LLC'));
insert into mnc(mcc,mnc,operator) values(313,340,trim('Dish Wireless'));
insert into mnc(mcc,mnc,operator) values(313,350,trim('Dish Wireless'));
insert into mnc(mcc,mnc,operator) values(313,360,trim('Dish Wireless'));
insert into mnc(mcc,mnc,operator) values(313,370,trim('Red Truck Wireless LLC'));
insert into mnc(mcc,mnc,operator) values(313,380,trim('OptimERA Inc.'));
insert into mnc(mcc,mnc,operator) values(313,390,trim('Altice USA Wireless Inc.'));
insert into mnc(mcc,mnc,operator) values(313,400,trim('Texoma Communications LLC'));
insert into mnc(mcc,mnc,operator) values(313,410,trim('Anterix'));
insert into mnc(mcc,mnc,operator) values(313,420,trim('Hudson Valley Wireless'));
insert into mnc(mcc,mnc,operator) values(313,440,trim('Arvig Enterprises, Inc.'));
insert into mnc(mcc,mnc,operator) values(313,450,trim('Spectrum Wireless Holdings LLC'));
insert into mnc(mcc,mnc,operator) values(313,460,trim('Mobi Inc.'));
insert into mnc(mcc,mnc,operator) values(313,470,trim('San Diego Gas and Electric Company'));
insert into mnc(mcc,mnc,operator) values(313,480,trim('Ready Wireless LLC'));
insert into mnc(mcc,mnc,operator) values(313,490,trim('Puloli Inc.'));
insert into mnc(mcc,mnc,operator) values(313,500,trim('Shelcomm Inc.'));
insert into mnc(mcc,mnc,operator) values(313,510,trim('Puerto Rico Telephone Company'));
insert into mnc(mcc,mnc,operator) values(313,520,trim('Florida Broadband Inc.'));
insert into mnc(mcc,mnc,operator) values(313,540,trim('Nokia Innovations US LLC'));
insert into mnc(mcc,mnc,operator) values(313,550,trim('Mile High Networks LLC'));
insert into mnc(mcc,mnc,operator) values(313,560,trim('Boldyn Networks Transit US LLC'));
insert into mnc(mcc,mnc,operator) values(313,570,trim('Cellular Network Partnership'));
insert into mnc(mcc,mnc,operator) values(313,580,trim('Telecall Telecommunications Corp.'));
insert into mnc(mcc,mnc,operator) values(313,590,trim('Southern Communications Services, Inc.'));
insert into mnc(mcc,mnc,operator) values(313,600,trim('ST Engineering iDirect'));
insert into mnc(mcc,mnc,operator) values(313,610,trim('Point Broadband Fiber Holding, LLC'));
insert into mnc(mcc,mnc,operator) values(313,620,trim('OmniProphis Corporation'));
insert into mnc(mcc,mnc,operator) values(313,630,trim('LICT Corporation'));
insert into mnc(mcc,mnc,operator) values(313,640,trim('Geoverse LLC'));
insert into mnc(mcc,mnc,operator) values(313,650,trim('Chevron USA, Inc.'));
insert into mnc(mcc,mnc,operator) values(313,660,trim('Hudson Valley Wireless'));
insert into mnc(mcc,mnc,operator) values(313,670,trim('Hudson Valley Wireless'));
insert into mnc(mcc,mnc,operator) values(313,680,trim('Hudson Valley Wireless'));
insert into mnc(mcc,mnc,operator) values(313,690,trim('Shenandoah Cable Television LLC'));
insert into mnc(mcc,mnc,operator) values(313,700,trim('Ameren Services Company'));
insert into mnc(mcc,mnc,operator) values(313,710,trim('Extent Systems'));
insert into mnc(mcc,mnc,operator) values(313,720,trim('1st Point Communications LLC'));
insert into mnc(mcc,mnc,operator) values(313,730,trim('TruAccess Networks'));
insert into mnc(mcc,mnc,operator) values(313,740,trim('RTO Wireless LLC'));
insert into mnc(mcc,mnc,operator) values(313,750,trim('CellTex Networks LLC'));
insert into mnc(mcc,mnc,operator) values(313,760,trim('Hologram Inc.'));
insert into mnc(mcc,mnc,operator) values(313,770,trim('Tango Networks'));
insert into mnc(mcc,mnc,operator) values(313,780,trim('Windstream Holdings'));
insert into mnc(mcc,mnc,operator) values(313,800,trim('Wireless Technologies of Nebraska'));
insert into mnc(mcc,mnc,operator) values(313,810,trim('Watch Communications'));
insert into mnc(mcc,mnc,operator) values(313,820,trim('Inland Cellular Telephone Company'));
insert into mnc(mcc,mnc,operator) values(313,830,trim('360 Communications'));
insert into mnc(mcc,mnc,operator) values(313,840,trim('CellBlox Acquisitions'));
insert into mnc(mcc,mnc,operator) values(313,850,trim('Softcom Internet Communications Inc'));
insert into mnc(mcc,mnc,operator) values(313,860,trim('AMG Technology Investment Group'));
insert into mnc(mcc,mnc,operator) values(313,870,trim('ElektraFi LLC'));
insert into mnc(mcc,mnc,operator) values(313,880,trim('Shuttle Wireless'));
insert into mnc(mcc,mnc,operator) values(313,890,trim('Tulare County Office of Education'));
insert into mnc(mcc,mnc,operator) values(313,900,trim('Tribal Networks'));
insert into mnc(mcc,mnc,operator) values(313,910,trim('San Diego Gas and Electric'));
insert into mnc(mcc,mnc,operator) values(313,920,trim('JCI'));
insert into mnc(mcc,mnc,operator) values(313,930,trim('Standing Rock Telecom'));
insert into mnc(mcc,mnc,operator) values(313,940,trim('Motorola Solutions'));
insert into mnc(mcc,mnc,operator) values(313,950,trim('Cheyenne and Arapaho Development Group'));
insert into mnc(mcc,mnc,operator) values(313,960,trim('Townes 5G LLC'));
insert into mnc(mcc,mnc,operator) values(313,970,trim('Tychron'));
insert into mnc(mcc,mnc,operator) values(313,980,trim('Next Generation Application LLC'));
insert into mnc(mcc,mnc,operator) values(313,990,trim('Ericsson US'));
insert into mnc(mcc,mnc,operator) values(314,10,trim('Boingo Wireless Inc.'));
insert into mnc(mcc,mnc,operator) values(314,20,trim('Spectrum Wireless Holdings LLC'));
insert into mnc(mcc,mnc,operator) values(314,30,trim('Baicells Technologies North America Inc.'));
insert into mnc(mcc,mnc,operator) values(314,60,trim('Texas AandM University'));
insert into mnc(mcc,mnc,operator) values(314,70,trim('Texas AandM University'));
insert into mnc(mcc,mnc,operator) values(314,80,trim('Texas AandM University'));
insert into mnc(mcc,mnc,operator) values(314,90,trim('Southern LINC'));
insert into mnc(mcc,mnc,operator) values(314,200,trim('XF Wireless Investments LLC'));
insert into mnc(mcc,mnc,operator) values(314,210,trim('Telecom Resource Center'));
insert into mnc(mcc,mnc,operator) values(314,220,trim('Securus Technologies'));
insert into mnc(mcc,mnc,operator) values(314,230,trim('Trace-Tek LLC'));
insert into mnc(mcc,mnc,operator) values(314,240,trim('XF Wireless Investments, LLC'));
insert into mnc(mcc,mnc,operator) values(314,260,trim('ATandT Mobility'));
insert into mnc(mcc,mnc,operator) values(314,270,trim('ATandT Mobility'));
insert into mnc(mcc,mnc,operator) values(314,280,trim('Pollen Mobile LLC'));
insert into mnc(mcc,mnc,operator) values(314,290,trim('Wave'));
insert into mnc(mcc,mnc,operator) values(314,300,trim('Southern California Edison'));
insert into mnc(mcc,mnc,operator) values(314,310,trim('Terranet'));
insert into mnc(mcc,mnc,operator) values(314,320,trim('Agri-Valley Communications Inc'));
insert into mnc(mcc,mnc,operator) values(314,330,trim('Nova Labs Inc'));
insert into mnc(mcc,mnc,operator) values(314,340,trim('E-Marconi LLC'));
insert into mnc(mcc,mnc,operator) values(314,350,trim('Evergy'));
insert into mnc(mcc,mnc,operator) values(314,360,trim('Oceus Networks LLC'));
insert into mnc(mcc,mnc,operator) values(314,370,trim('Texas AandM University'));
insert into mnc(mcc,mnc,operator) values(314,380,trim('Circle Computer Resources Inc.'));
insert into mnc(mcc,mnc,operator) values(314,390,trim('ATandT Mobility'));
insert into mnc(mcc,mnc,operator) values(314,400,trim('Cellular South Inc'));
insert into mnc(mcc,mnc,operator) values(314,410,trim('Peeringhub Inc'));
insert into mnc(mcc,mnc,operator) values(314,420,trim('Cox Communications'));
insert into mnc(mcc,mnc,operator) values(314,430,trim('Highway9 Networks Inc'));
insert into mnc(mcc,mnc,operator) values(314,440,trim('Tecore Global Services LLC'));
insert into mnc(mcc,mnc,operator) values(314,450,trim('NUWAVE Communications Inc.'));
insert into mnc(mcc,mnc,operator) values(314,460,trim('Texas AandM University'));
insert into mnc(mcc,mnc,operator) values(314,470,trim('Manhattan Telecommunications Corporation LLC'));
insert into mnc(mcc,mnc,operator) values(314,480,trim('Xcel Energy Services Inc.'));
insert into mnc(mcc,mnc,operator) values(314,490,trim('Utah Education and Telehealth Network'));
insert into mnc(mcc,mnc,operator) values(314,500,trim('Aetheros Inc.'));
insert into mnc(mcc,mnc,operator) values(314,510,trim('SI Wireless LLC'));
insert into mnc(mcc,mnc,operator) values(314,520,trim('Oklahoma Gas and Electric Company'));
insert into mnc(mcc,mnc,operator) values(314,530,trim('Agile Networks'));
insert into mnc(mcc,mnc,operator) values(314,540,trim('RGTN USA Inc.'));
insert into mnc(mcc,mnc,operator) values(315,10,trim('Citizens Broadband Radio Service'));
insert into mnc(mcc,mnc,operator) values(316,10,trim('Nextel Communications'));
insert into mnc(mcc,mnc,operator) values(316,11,trim('Southern Communications Services'));
insert into mnc(mcc,mnc,operator) values(316,700,trim('Mile High Networks LLC'));
insert into mnc(mcc,mnc,operator) values(310,410,trim('Liberty'));

