version: '3'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--log.level=debug'
    networks:
      - monitoring

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    hostname: 192.168.1.104
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager:/etc/alertmanager
      - /etc/hosts:/etc/hosts
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--log.level=debug'
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin_password
    volumes:
      - ./grafana:/var/lib/grafana
      - ./etc/grafana/grafana.ini:/etc/grafana/grafana.ini
    depends_on:
      - prometheus
    networks:
      - monitoring

  nginx:
    image: nginx:alpine
    ports:
      - "7001:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
    depends_on:
      - prometheus
    networks:
      - monitoring

networks:
  monitoring:

