 CREATE TABLE `deliveries_20230701` (
  `cli_id` bigint(16) NOT NULL,
  `platform_cluster` varchar(10) NOT NULL,
  `sms_priority` tinyint(1) NOT NULL,
  `dn_hdr` varchar(15) DEFAULT NULL,
  `dest` bigint(15) DEFAULT NULL,
  `base_msg_id` varchar(25) NOT NULL,
  `msg_id` varchar(25) NOT NULL,
  `file_id` varchar(25) DEFAULT NULL,
  `recv_time` datetime(3) NOT NULL,
  `recv_date` date NOT NULL,
  `act_recv_time` datetime(3) NOT NULL,
  `act_recv_date` date NOT NULL,
  `carrier_datetime_format` varchar(15) DEFAULT NULL,
  `msg_part_no` tinyint(3) DEFAULT NULL,
  `total_msg_parts` tinyint(3) DEFAULT NULL,
  `retry_attempt` tinyint(1) DEFAULT NULL,
  `act_route_id` varchar(6) DEFAULT NULL,
  `dlr_from_internal` tinyint(1) DEFAULT NULL,
  `route_logic_id` varchar(3) DEFAULT NULL,
  `route_id` varchar(6) DEFAULT NULL,
  `smsc_id` varchar(20) DEFAULT NULL,
  `carrier_full_dn` varchar(2000) DEFAULT NULL,
  `dly_time` datetime(3) DEFAULT NULL,
  `act_dly_time` datetime(3) DEFAULT NULL,
  `carrier_rcvd_time` datetime(3) DEFAULT NULL,
  `carrier_ack_id` varchar(100) DEFAULT NULL,
  `carrier_sys_id` varchar(20) DEFAULT NULL,
  `term_carrier` varchar(200) DEFAULT NULL,
  `term_circle` varchar(200) DEFAULT NULL,
  `delv_lat_ori_in_millis` bigint(10) DEFAULT NULL,
  `delv_lat_sla_in_millis` bigint(10) DEFAULT NULL,
  `overall_lat_in_millis` bigint(10) DEFAULT NULL,
  `dlr_type` tinyint(1) DEFAULT NULL,
  `dn_ori_sts_code` varchar(5) NOT NULL,
  `dn_cli_sts_code` varchar(5) NOT NULL,
  `dn_ori_sts_desc` varchar(100) NOT NULL,
  `dn_cli_sts_desc` varchar(100) NOT NULL,
  `car_ori_sts_code` varchar(5) DEFAULT NULL,
  `car_ori_sts_desc` varchar(10) DEFAULT NULL,
  `car_sts_code` varchar(100) DEFAULT NULL,
  `car_sts_desc` varchar(100) DEFAULT NULL,
  `retry_ori_route_id` varchar(6) DEFAULT NULL,
  `retry_alt_route_id` varchar(6) DEFAULT NULL,
  `delivery_status` varchar(10) DEFAULT NULL,
  `car_delivery_status` varchar(10) DEFAULT NULL COMMENT 'Carrier Delivery Status',
  `sms_rate` decimal(10,4) NOT NULL DEFAULT 0.0000 COMMENT 'Sms rate per message',
  `dlt_rate` decimal(10,4) NOT NULL DEFAULT 0.0000 COMMENT 'Dlt rate per message',
  `created_ts` datetime NOT NULL DEFAULT current_timestamp(),
  `billing_sms_rate` decimal(16,12) NOT NULL DEFAULT 0.000000000000,
  `billing_add_fixed_rate` decimal(16,12) NOT NULL DEFAULT 0.000000000000 COMMENT 'Billing Additional Fixed Rate',
  `base_sms_rate` decimal(16,12) NOT NULL DEFAULT 0.000000000000 COMMENT 'Base SMS Rate',
  `base_add_fixed_rate` decimal(16,12) NOT NULL DEFAULT 0.000000000000 COMMENT 'Base Additional Fixed Rate',
  `ref_sms_rate` decimal(16,12) NOT NULL DEFAULT 0.000000000000 COMMENT 'Reference SMS Rate',
  `ref_add_fixed_rate` decimal(16,12) NOT NULL DEFAULT 0.000000000000 COMMENT 'Reference Additional Fixed Rate',
  KEY `msg_id` (`msg_id`),
  KEY `recv_time` (`recv_time`),
  KEY `cli_id` (`cli_id`),
  KEY `dest` (`dest`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 




