
CREATE TABLE `interim_failures_20230701` (
  `cli_id` bigint(16) NOT NULL,
  `file_id` varchar(25) DEFAULT NULL,
  `msg_id` varchar(25) NOT NULL,
  `dest` bigint(15) DEFAULT NULL,
  `recv_date` date NOT NULL,
  `recv_time` datetime(3) NOT NULL,
  `retry_attempt` tinyint(1) DEFAULT NULL,
  `msg_type` tinyint(1) NOT NULL,
  `route_id` varchar(6) DEFAULT NULL,
  `retry_ori_route_id` varchar(6) DEFAULT NULL,
  `sms_priority` tinyint(1) NOT NULL,
  `carrier_rcvd_time` datetime(3) DEFAULT NULL,
  `carrier_ack_id` varchar(100) DEFAULT NULL,
  `carrier_sys_id` varchar(20) DEFAULT NULL,
  `carrier_full_dn` varchar(2000) DEFAULT NULL,
  `hdr` varchar(15) DEFAULT NULL,
  `msg_part_no` tinyint(3) DEFAULT NULL,
  `bill_type` tinyint(1) NOT NULL,
  `company` varchar(150) DEFAULT NULL,
  `msg_class` varchar(5) DEFAULT NULL,
  `circle` varchar(200) DEFAULT NULL,
  `carrier` varchar(200) DEFAULT NULL,
  `term_carrier` varchar(200) DEFAULT NULL,
  `term_circle` varchar(200) DEFAULT NULL,
  `country` varchar(20) DEFAULT NULL,
  `alpha` tinyint(4) DEFAULT NULL,
  `dn_ori_sts_code` varchar(5) NOT NULL,
  `dn_ori_sts_desc` varchar(100) NOT NULL,
  `car_ori_sts_code` varchar(5) DEFAULT NULL,
  `car_ori_sts_desc` varchar(100) DEFAULT NULL,
  `msg_credits` decimal(10,3) DEFAULT NULL,
  `dlt_credits` decimal(10,3) DEFAULT NULL,
  `delivery_status` varchar(10) DEFAULT NULL,
  `created_ts` datetime(3) NOT NULL DEFAULT current_timestamp(3),
  KEY `msg_id` (`msg_id`),
  KEY `recv_time` (`recv_time`),
  KEY `dest` (`dest`),
  KEY `cli_id` (`cli_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1

