
CREATE TABLE `submission_20230701` (
  `intf_type` varchar(10) NOT NULL,
  `intf_grp_type` varchar(10) NOT NULL,
  `msg_source` varchar(25) NOT NULL COMMENT 'Message Source',
  `intl_msg` tinyint(1) NOT NULL,
  `cli_id` bigint(16) NOT NULL,
  `msg_type` tinyint(1) NOT NULL,
  `platform_cluster` varchar(10) NOT NULL,
  `sms_priority` tinyint(1) NOT NULL,
  `bill_encrypt_type` tinyint(1) NOT NULL,
  `bill_type` tinyint(1) NOT NULL,
  `app_type` varchar(10) NOT NULL,
  `msg` mediumtext DEFAULT NULL,
  `udhi` tinyint(1) DEFAULT NULL,
  `udh` varchar(15) DEFAULT NULL,
  `dcs` varchar(3) DEFAULT NULL,
  `hdr` varchar(15) DEFAULT NULL,
  `dest` bigint(15) DEFAULT NULL,
  `msg_id` varchar(25) NOT NULL,
  `file_id` varchar(25) DEFAULT NULL,
  `base_msg_id` varchar(25) NOT NULL,
  `cli_msg_id` varchar(50) DEFAULT NULL,
  `recv_time` datetime(3) NOT NULL,
  `recv_date` date NOT NULL,
  `act_recv_time` datetime(3) NOT NULL,
  `act_recv_date` date NOT NULL,
  `cli_max_split` tinyint(2) DEFAULT 0,
  `msg_tag` varchar(50) DEFAULT NULL,
  `is_hex_msg` tinyint(1) DEFAULT 0,
  `max_validity_in_sec` int(10) DEFAULT NULL,
  `cli_ip` varchar(30) NOT NULL,
  `msg_class` varchar(5) DEFAULT NULL,
  `country` varchar(20) DEFAULT NULL,
  `param1` varchar(50) DEFAULT NULL,
  `param2` varchar(50) DEFAULT NULL,
  `param3` varchar(50) DEFAULT NULL,
  `param4` varchar(50) DEFAULT NULL,
  `param5` varchar(50) DEFAULT NULL,
  `param6` varchar(100) DEFAULT NULL,
  `param7` varchar(100) DEFAULT NULL,
  `param8` varchar(100) DEFAULT NULL,
  `param9` varchar(250) DEFAULT NULL,
  `param10` varchar(500) DEFAULT NULL,
  `sch_date_time` datetime DEFAULT NULL,
  `cli_dlt_tmpl_id` bigint(19) DEFAULT NULL,
  `dlt_tmpl_id` bigint(19) DEFAULT NULL,
  `cli_dlt_entity_id` bigint(19) DEFAULT NULL,
  `dlt_entity_id` bigint(19) DEFAULT NULL,
  `app_ins_id` varchar(5) DEFAULT NULL,
  `blkout_type` varchar(10) DEFAULT NULL,
  `msg_part_no` tinyint(3) DEFAULT NULL,
  `total_msg_parts` tinyint(3) DEFAULT NULL,
  `feature_code` varchar(5) DEFAULT NULL,
  `cli_tmpl_id` bigint(19) DEFAULT NULL,
  `retry_attempt` tinyint(1) DEFAULT NULL,
  `shortner_id` varchar(100) DEFAULT NULL,
  `msg_shortned` tinyint(1) DEFAULT NULL,
  `route_id` varchar(6) DEFAULT NULL,
  `act_route_id` varchar(6) DEFAULT NULL,
  `circle` varchar(200) DEFAULT NULL,
  `carrier` varchar(200) DEFAULT NULL,
  `carrier_sub_time` datetime(3) DEFAULT NULL,
  `act_carrier_sub_time` datetime(3) DEFAULT NULL,
  `aplha_value` varchar(15) DEFAULT NULL,
  `cli_hdr` varchar(15) DEFAULT NULL,
  `intf_country_code` varchar(5) DEFAULT NULL,
  `route_logic_id` varchar(3) DEFAULT NULL,
  `masked_hdr` varchar(15) DEFAULT NULL,
  `smsc_id` varchar(20) DEFAULT NULL,
  `dlr_type` tinyint(1) DEFAULT NULL,
  `encrypted_msg` mediumtext DEFAULT NULL,
  `encrypted_dest` varchar(100) DEFAULT NULL,
  `sub_lat_ori_in_millis` bigint(10) DEFAULT NULL,
  `sub_lat_sla_in_millis` bigint(10) DEFAULT NULL,
  `file_name` varchar(500) DEFAULT NULL,
  `campaign_id` varchar(36) DEFAULT NULL,
  `campaign_name` varchar(50) DEFAULT NULL,
  `msg_tag1` varchar(50) DEFAULT NULL,
  `msg_tag2` varchar(50) DEFAULT NULL,
  `msg_tag3` varchar(50) DEFAULT NULL,
  `msg_tag4` varchar(50) DEFAULT NULL,
  `msg_tag5` varchar(50) DEFAULT NULL,
  `sub_ori_sts_code` varchar(5) NOT NULL,
  `sub_cli_sts_code` varchar(5) NOT NULL,
  `sub_ori_sts_desc` varchar(100) NOT NULL,
  `sub_cli_sts_desc` varchar(100) NOT NULL,
  `sub_status` varchar(10) DEFAULT NULL COMMENT 'Submission Status',
  `sms_rate` decimal(10,4) NOT NULL DEFAULT 0.0000 COMMENT 'SMS Rate per message',
  `dlt_rate` decimal(10,4) NOT NULL DEFAULT 0.0000 COMMENT 'Dlt rate per message',
  `add_error_info` mediumtext DEFAULT NULL,
  `created_ts` datetime(3) NOT NULL DEFAULT current_timestamp(3),
  `billing_currency` varchar(3) DEFAULT NULL COMMENT 'billing currency',
  `billing_sms_rate` decimal(16,12) NOT NULL DEFAULT 0.000000000000,
  `billing_add_fixed_rate` decimal(16,12) NOT NULL DEFAULT 0.000000000000 COMMENT 'Billing Additional Fixed Rate',
  `base_currency` varchar(5) DEFAULT NULL COMMENT 'Base Currency',
  `base_sms_rate` decimal(16,12) NOT NULL DEFAULT 0.000000000000 COMMENT 'Base SMS Rate',
  `base_add_fixed_rate` decimal(16,12) NOT NULL DEFAULT 0.000000000000 COMMENT 'Base Additional Fixed Rate',
  `ref_currency` varchar(5) DEFAULT NULL COMMENT 'Refrence Currency',
  `ref_sms_rate` decimal(16,12) NOT NULL DEFAULT 0.000000000000 COMMENT 'Refrence SMS Rate',
  `ref_add_fixed_rate` decimal(16,12) NOT NULL DEFAULT 0.000000000000 COMMENT 'Refrence Additional Fixed Rate',
  `billing_exchange_rate` decimal(16,12) NOT NULL DEFAULT 0.000000000000 COMMENT 'Billing Exchange Rate',
  `ref_exchange_rate` decimal(16,12) NOT NULL DEFAULT 0.000000000000 COMMENT 'Refrece Exchange Rate',
  `smpp_recv_time` datetime(3) DEFAULT NULL COMMENT 'Smpp Actival Received Time',
  KEY `msg_id` (`msg_id`),
  KEY `recv_time` (`recv_time`),
  KEY `cli_id` (`cli_id`),
  KEY `base_msg_id` (`base_msg_id`),
  KEY `dest` (`dest`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
