CREATE TABLE `su_config` (
  `cli_id` bigint(16) NOT NULL COMMENT 'Client Id for Super User',
  `bill_type` tinyint(1) NOT NULL DEFAULT 1 COMMENT '0-Postpaid, 1-Prepaid',
  `msg_type` tinyint(1) NOT NULL DEFAULT 1 COMMENT '0-Promotional, 1-Tansactional',
  `acc_status` tinyint(1) DEFAULT 0 COMMENT 'ACTIVE(0), DEACTIVATED(1), EXPIRY(2), SUSPENDED(3), INACTIVE(4)',
  `acc_route_id` varchar(6) DEFAULT NULL COMMENT 'Default route id for the client',
  `platform_cluster` varchar(10) DEFAULT NULL COMMENT 'Account belongs to the specific cluster',
  `sms_priority` tinyint(1) NOT NULL DEFAULT 5 COMMENT 'Default SMS priority',
  `sms_retry_available` tinyint(1) DEFAULT 0 COMMENT '0-Retry Not available,1-global, 2-same route, 3-custom',
  `sms_bill_on_sub` tinyint(1) NOT NULL DEFAULT 1 COMMENT '0-Not available, 1-Available',
  `newline_replace_char` varchar(3) DEFAULT NULL COMMENT 'A set of characters to be replaced as a new line in the request',
  `is_16bit_udh` tinyint(1) NOT NULL DEFAULT 0 COMMENT '0-Disabled, 1-Enabled. Used to create UDH Generation for multipart messages',
  `acknowledge_id_length` tinyint(2) DEFAULT 22 COMMENT 'Length of the acknowledge id given to client',
  `client_encrypt` tinyint(1) NOT NULL DEFAULT 0 COMMENT 'On request Message (Message only) encryoted. 0-Disabled, 1-Encrypted',
  `bill_encrypt_type` tinyint(1) DEFAULT 0 COMMENT '0-Disabled, 1-Encrypt Messages only 2-Encrypt Mobile Only, 3- Encrypt Message and Mobile',
  `domestic_promo_trai_blockout_purge` tinyint(1) NOT NULL DEFAULT 0 COMMENT '0-Process the domestic message in next day, 1-Discard the message',
  `domestic_sms_blockout` tinyint(1) DEFAULT 0 COMMENT '0-Disabled, 1-Process the domestic message after blockout time, 2-Discard the message with in the blockout time',
  `domestic_sms_blockout_start` varchar(5) DEFAULT NULL COMMENT 'Client specific blockout start time for Domestic Message',
  `domestic_sms_blockout_stop` varchar(5) DEFAULT NULL COMMENT 'Client specific blockout end time for Domestic Message',
  `dlt_templ_grp_id` bigint(20) DEFAULT NULL,
  `dnd_chk` tinyint(1) DEFAULT 0 COMMENT '0-Disabled,1-Enabled',
  `dnd_pref` tinyint(1) NOT NULL DEFAULT 0 COMMENT 'DND Preferences for this client',
  `blklist_chk` tinyint(1) DEFAULT 1 COMMENT '0-Disabled, 1-Enabled. If enabled refer the global mobile block for blocking',
  `spam_chk` tinyint(1) DEFAULT 2 COMMENT '0-Disabled, 1-Enabled, 2-Enabled and log the spam information',
  `dup_chk_req` tinyint(1) NOT NULL DEFAULT 0 COMMENT '0-Disabled, 1-Enabled based on Client Ref Id, 2-Enabled based on Mobile and Message',
  `dup_chk_interval` int(10) NOT NULL DEFAULT 0 COMMENT 'Interval time for the duplicate check.',
  `intl_sms_blockout` tinyint(1) DEFAULT 0 COMMENT '0-Disabled, 1-Process the international message after blockout time, 2-Discard the message with in the blockout time',
  `intl_sms_blockout_start` varchar(5) DEFAULT NULL COMMENT 'Client specific blockout start time for international Message',
  `intl_sms_blockout_stop` varchar(5) DEFAULT NULL COMMENT 'Client specific blockout end time for international Message',
  `retry_alter_route_lookup` tinyint(1) DEFAULT 1 COMMENT '0-Disabled, 1-Enabled',
  `time_zone` varchar(200) DEFAULT NULL COMMENT 'Default timezone for the Client',
  `time_offset` varchar(10) DEFAULT NULL COMMENT 'Timezone offset value from GMT',
  `two_level_auth` tinyint(1) DEFAULT 0,
  `mt_adjust` int(1) DEFAULT 0,
  `dn_adjust` int(1) DEFAULT 0,
  `optin_chk_req` tinyint(1) NOT NULL DEFAULT 0,
  `created_ts` datetime DEFAULT current_timestamp(),
  `created_user` varchar(50) DEFAULT NULL,
  `updated_ts` datetime DEFAULT current_timestamp(),
  `modified_user` varchar(50) DEFAULT NULL,
  `sales_id` int(10) NOT NULL DEFAULT 0,
  `credit_check` tinyint(1) NOT NULL DEFAULT 0 COMMENT '0 - Disabled, 1 - Enabled',
  `credit_limit` decimal(16,4) NOT NULL DEFAULT 0.0000 COMMENT 'Max Credit Limit for Post Paid Customers',
  PRIMARY KEY (`cli_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 

