CREATE TABLE `user_config` (
  `cli_id` bigint(16) NOT NULL COMMENT 'Client Id for User',
  `firstname` varchar(50) DEFAULT NULL COMMENT 'First Name of the client',
  `lastname` varchar(50) DEFAULT NULL COMMENT 'Last Name of the client',
  `email` varchar(100) DEFAULT NULL COMMENT 'Email id for the client',
  `mobile` bigint(15) DEFAULT NULL COMMENT 'Mobile number for the client',
  `company` varchar(200) DEFAULT NULL COMMENT 'Company of the client',
  `address` varchar(200) DEFAULT NULL,
  `user` varchar(50) NOT NULL COMMENT 'Username for this User',
  `ui_pass` varchar(100) NOT NULL COMMENT 'Password for UI Customer',
  `api_pass` varchar(100) NOT NULL DEFAULT 'mgMitUQEQXQY8n8icGQNLGdPbDJTelRya3HockS6fHWBNzq/L0seqINs' COMMENT 'Password for API Customer',
  `smpp_pass` varchar(100) NOT NULL DEFAULT '5hu0iYPlsgzzyLF8fl7KXWtJTDExNzIha0oEvGKCGlDB0bPbZ8yQ0cgz' COMMENT 'Password for SMPP Customer',
  `user_type` tinyint(1) NOT NULL COMMENT '0-Super User,1-Admin User, 2-User. Type of the User.',
  `pu_id` bigint(16) NOT NULL COMMENT 'Parent User Id',
  `su_id` bigint(16) NOT NULL COMMENT 'Super User Id',
  `first_activation_date` datetime DEFAULT current_timestamp() COMMENT 'First activation date',
  `activation_date` datetime NOT NULL DEFAULT current_timestamp() COMMENT 'Last activation date',
  `acc_status` tinyint(1) NOT NULL DEFAULT 0 COMMENT 'ACTIVE(0), DEACTIVATED(1), EXPIRY(2), SUSPENDED(3), INACTIVE(4), INVALID(5)',
  `acc_route_id` varchar(6) DEFAULT NULL COMMENT 'Default route id for the client',
  `platform_cluster` varchar(10) DEFAULT NULL COMMENT 'Account belongs to the specific Platform cluster',
  `sms_priority` tinyint(1) DEFAULT NULL COMMENT 'Default SMS priority',
  `newline_replace_char` varchar(3) DEFAULT NULL COMMENT 'A set of characters to be replaced as a new line in the request',
  `is_16bit_udh` tinyint(1) DEFAULT NULL COMMENT '0-Disabled, 1-Enabled. Used to create UDH Generation for multipart messages',
  `acknowledge_id_length` tinyint(2) DEFAULT NULL COMMENT 'Length of the acknowledge id given to Client',
  `client_encrypt` tinyint(1) DEFAULT NULL COMMENT 'On request Message (Message only) encryoted. 0-Disabled, 1-Encrypted',
  `bill_encrypt_type` tinyint(1) DEFAULT NULL COMMENT '0-Disabled, 1-Enabled ( Refer configuration.client_crypto_info table)',
  `domestic_promo_trai_blockout_purge` tinyint(1) DEFAULT NULL COMMENT '0-Process the domestic message in next day, 1-Discard the message',
  `domestic_sms_blockout` tinyint(1) DEFAULT 0 COMMENT '0-Disabled, 1-Process the domestic message after blockout time, 2-Discard the message with in the blockout time',
  `domestic_sms_blockout_start` varchar(5) DEFAULT NULL COMMENT 'Client specific blockout start time for Domestic Message',
  `domestic_sms_blockout_stop` varchar(5) DEFAULT NULL COMMENT 'Client specific blockout end time for Domestic Message',
  `dlt_templ_grp_id` bigint(20) DEFAULT NULL,
  `dup_chk_req` tinyint(1) DEFAULT NULL COMMENT '0-Disabled, 1-Enabled based on Client Ref Id, 2-Enabled based on Mobile and Message',
  `dup_chk_interval` int(10) DEFAULT NULL COMMENT 'Interval time for the duplicate check.',
  `intl_sms_blockout` tinyint(1) DEFAULT 0 COMMENT '0-Disabled, 1-Process the international message after blockout time, 2-Discard the message with in the blockout time',
  `intl_sms_blockout_start` varchar(5) DEFAULT NULL COMMENT 'Client specific blockout start time for international Message',
  `intl_sms_blockout_stop` varchar(5) DEFAULT NULL COMMENT 'Client specific blockout end time for international Message',
  `retry_alter_route_lookup` tinyint(1) DEFAULT 1 COMMENT '0-Disabled, 1-Enabled',
  `time_zone` varchar(200) DEFAULT NULL COMMENT 'Default timezone for the Client',
  `time_offset` varchar(10) DEFAULT NULL COMMENT 'Timezone offset value from GMT',
  `two_level_auth` tinyint(1) DEFAULT NULL,
  `ip_validation` tinyint(1) NOT NULL DEFAULT 0,
  `ip_list` varchar(2000) DEFAULT NULL,
  `mt_adjust` int(1) DEFAULT 0,
  `dn_adjust` int(1) DEFAULT 0,
  `dnd_reject_yn` tinyint(1) DEFAULT 0,
  `vl_shortner` tinyint(1) DEFAULT 0,
  `msg_replace_chk` tinyint(1) NOT NULL DEFAULT 0,
  `is_schedule_allow` tinyint(1) NOT NULL DEFAULT 0 COMMENT '0 - Disabled, 1 - Allowed',
  `uc_iden_allow` tinyint(1) NOT NULL DEFAULT 0 COMMENT '0 - Disable, 1 - Enable',
  `uc_iden_char_len` tinyint(2) NOT NULL DEFAULT 1 COMMENT 'Number of characters to identify the Unicode Message',
  `uc_iden_occur` tinyint(1) NOT NULL DEFAULT 1 COMMENT 'Number of occurance of consigitive Uinicode char spcified in ''uc_iden_char_len''',
  `is_remove_uc_chars` tinyint(1) NOT NULL DEFAULT 0 COMMENT 'Remove identifyed Unicode chars',
  `url_smartlink_enable` tinyint(1) NOT NULL DEFAULT 0,
  `url_track_enabled` tinyint(1) NOT NULL DEFAULT 0,
  `vl_shortcode_len` tinyint(1) NOT NULL DEFAULT 6,
  `is_async` tinyint(1) NOT NULL DEFAULT 1 COMMENT '0 - Sync, 1 - Async',
  `use_default_header` tinyint(1) NOT NULL DEFAULT 0 COMMENT '0 - Disabled, 1 - Enabled',
  `use_default_on_header_fail` tinyint(1) NOT NULL DEFAULT 0 COMMENT '0 - Disabled , 1 - Enabled',
  `acc_default_header` varchar(15) NOT NULL DEFAULT 'DEVTST' COMMENT 'Client Default Header',
  `considerdefaultlength_as_domestic` tinyint(1) NOT NULL DEFAULT 0 COMMENT '0 - Disable, 1 - Enable',
  `domestic_tra_blockout_reject` tinyint(1) NOT NULL DEFAULT 1 COMMENT '0-Accept During TRAI Blockout at Interface level,1-Reject During TRAI Blockout  at Interface level',
  `timebound_chk_enable` tinyint(1) NOT NULL DEFAULT 0 COMMENT '0 - Disabled, 1 - Enabled',
  `timebound_interval` int(10) DEFAULT 0 COMMENT 'Time bound interval in seconds',
  `timebound_max_count_allow` int(10) NOT NULL DEFAULT 0 COMMENT 'Time bound max request count allow',
  `sms_rate` decimal(10,4) NOT NULL DEFAULT 0.0000 COMMENT 'SMS Rate per message',
  `dlt_rate` decimal(10,4) NOT NULL DEFAULT 0.0000 COMMENT 'DLT Rate per message',
  `domestic_special_series_allow` tinyint(1) NOT NULL DEFAULT 0 COMMENT 'Domestic Special Numbers allow',
  `req_hex_msg` tinyint(1) NOT NULL DEFAULT 0 COMMENT 'Customer Sends Hex String in Message',
  `last_pwd_change` datetime DEFAULT NULL,
  `created_ts` datetime DEFAULT current_timestamp(),
  `created_user` varchar(50) DEFAULT NULL,
  `updated_ts` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `modified_user` varchar(50) DEFAULT NULL,
  `acc_type` tinyint(1) NOT NULL DEFAULT 1 COMMENT '1-Test, 2-Demo, 0-Production',
  `invoice_based_on` tinyint(1) NOT NULL DEFAULT 0 COMMENT '0-Submission, 1-Deliveries',
  `base_sms_rate` decimal(16,12) NOT NULL DEFAULT 0.000000000000 COMMENT 'Base SMS Rate',
  `base_add_fixed_rate` decimal(16,12) NOT NULL DEFAULT 0.000000000000 COMMENT 'Base Additionl Fixed Rate',
  `billing_currency_conv_type` tinyint(1) NOT NULL DEFAULT 2 COMMENT '1 - Monthly , 2 - Daily',
  `is_ildo` tinyint(1) NOT NULL DEFAULT 0 COMMENT '0 - Non ildo, 1 - ildo',
  `dnd_pref` int(1) NOT NULL DEFAULT 0 COMMENT 'DND Preferences for this client',
  `force_dnd_check` tinyint(1) NOT NULL DEFAULT 0 COMMENT '0 - Disabled , 1 - Enable Force DND Check',
  `billing_currency` varchar(3) NOT NULL DEFAULT 'INR' COMMENT 'billing currency value',
  `msg_retry_available` tinyint(1) NOT NULL DEFAULT 1 COMMENT '0 - No Msg Retry, 1 - Single Part Only, 2 - Single and Multipart , 3 - Partial Failed Retry',
  `capping_chk_enable` tinyint(1) NOT NULL DEFAULT 0 COMMENT '0 - Disabled, 1 - Enabled',
  `capping_interval_type` tinyint(1) NOT NULL DEFAULT 0 COMMENT '0 - None, 1 - Minute, 2 - Hour, 3 - Date, 4 - Week, 5- Month, 6 - Year',
  `capping_interval` int(10) DEFAULT 0 COMMENT 'Capping Interval based on Interval Type',
  `capping_max_count_allow` bigint(15) DEFAULT 0 COMMENT 'Capping Max Count Allow',
  `credit_check` tinyint(1) NOT NULL DEFAULT 0 COMMENT '0 - Disabled, 1 - Enabled',
  `credit_limit` decimal(16,4) NOT NULL DEFAULT 0.0000 COMMENT 'Max Credit Limit for Post Paid Customers',
  `expiry_date` datetime DEFAULT NULL,
  `blklist_chk` tinyint(1) NOT NULL DEFAULT 0 COMMENT '0 - Disabled, 1 - Gobal Level Only, 2 - User Level Only, 3 - User then Global only, 4 - User then Admin then Super Admin only, 5 - User then Admin then Super Admin then Global, 6 - User then Parent User then Grand Parent User only, 7 - User then Parent User then Grand Parent User then Global',
  `spam_chk` tinyint(1) NOT NULL DEFAULT 0 COMMENT '0 - Disabled, 1 - Global Only, 2 - MsgType Only, 3 - Client Level Only, 4 - ALL (Client Level, MsgType, Global)',
  PRIMARY KEY (`cli_id`),
  UNIQUE KEY `user_config_user_uindex` (`user`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1
