version: '3'

services:
  dns-server:
    image: sameersbn/bind:latest
    container_name: dns-server
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./bind/config:/data/bind/etc
    environment:
      - TZ=UTC
    networks:
      - dns-net

  dns-admin:
    image: phpmyadmin/phpmyadmin
    container_name: dns-admin
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - dns-server
    networks:
      - dns-net

networks:
  dns-net:

